[book]
authors = ["OpenPacketCore Contributors"]
language = "en"
src = "docs"
title = "OpenPacketCore SDK Documentation"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/openpacketcore/openpacketcore-sdk"
