//! Independent wire evidence for TS 29.273 RAR/RAA and AAR/AAA.
//!
//! The input fixtures are hand-authored from RFC 6733 framing and TS 29.273
//! sections 7.2.2.4 and 7.2.2.1. They are not generated by the SDK builders.

use bytes::BytesMut;
use opc_proto_diameter::apps::swm::{
    self, AuthRequestType, SwmAarFlags, SwmAcceptedAuthorizationUpdate, SwmAdditionalAvp,
    SwmAuthorizationRequest, SwmDiameterConnectionToken, SwmDiameterResult, SwmDiameterTransaction,
    SwmExpectedAnswerPeer, SwmHighPriorityAccessInfo, SwmReAuthAnswer, SwmReAuthRequest,
    SwmReAuthRequestEnvelope, SwmReAuthRequestType, SwmReAuthResult,
};
use opc_proto_diameter::apps::{self, VENDOR_ID_3GPP};
use opc_proto_diameter::avp::dictionary::Redacted;
use opc_proto_diameter::base;
use opc_proto_diameter::{
    AvpCode, AvpHeader, AvpKey, CommandKind, Message, OwnedMessage, DIAMETER_HEADER_LEN,
};
use opc_protocol::{
    BorrowDecode, DecodeContext, DecodeError, DecodeErrorCode, Encode, EncodeContext,
    EncodeErrorCode, UnknownIePolicy,
};
use std::{
    net::{IpAddr, Ipv4Addr},
    num::NonZeroU64,
};

const HOP_RAR: u32 = 0x3512_5801;
const END_RAR: u32 = 0x3512_5802;
const HOP_AAR: u32 = 0x3512_6501;
const END_AAR: u32 = 0x3512_6502;
const HOP_FAILOVER: u32 = 0x3512_65f1;
const CONNECTION_A: SwmDiameterConnectionToken = SwmDiameterConnectionToken::new(NonZeroU64::MIN);
const CONNECTION_B: SwmDiameterConnectionToken = SwmDiameterConnectionToken::new(
    NonZeroU64::new(2).expect("two is a nonzero connection generation"),
);
const SESSION: &str = "session;private;authorization-351";
const USER: &str = "subscriber-private@example.invalid";
const UNKNOWN: u32 = 93_510;

fn avp(code: AvpCode, flags: u8, value: &[u8]) -> Vec<u8> {
    let length = 8 + value.len();
    let mut wire = Vec::with_capacity((length + 3) & !3);
    wire.extend_from_slice(&code.get().to_be_bytes());
    wire.push(flags);
    wire.extend_from_slice(&(length as u32).to_be_bytes()[1..]);
    wire.extend_from_slice(value);
    wire.resize((length + 3) & !3, 0);
    wire
}

fn vendor_avp(code: AvpCode, flags: u8, value: &[u8]) -> Vec<u8> {
    let length = 12 + value.len();
    let mut wire = Vec::with_capacity((length + 3) & !3);
    wire.extend_from_slice(&code.get().to_be_bytes());
    wire.push(flags | 0x80);
    wire.extend_from_slice(&(length as u32).to_be_bytes()[1..]);
    wire.extend_from_slice(&VENDOR_ID_3GPP.get().to_be_bytes());
    wire.extend_from_slice(value);
    wire.resize((length + 3) & !3, 0);
    wire
}

fn message(
    command: u32,
    flags: u8,
    hop: u32,
    end: u32,
    avps: impl IntoIterator<Item = Vec<u8>>,
) -> Vec<u8> {
    let body: Vec<u8> = avps.into_iter().flatten().collect();
    let length = DIAMETER_HEADER_LEN + body.len();
    let mut wire = Vec::with_capacity(length);
    wire.push(1);
    wire.extend_from_slice(&(length as u32).to_be_bytes()[1..]);
    wire.push(flags);
    wire.extend_from_slice(&command.to_be_bytes()[1..]);
    wire.extend_from_slice(&swm::APPLICATION_ID.get().to_be_bytes());
    wire.extend_from_slice(&hop.to_be_bytes());
    wire.extend_from_slice(&end.to_be_bytes());
    wire.extend_from_slice(&body);
    wire
}

fn proxy_info() -> Vec<u8> {
    let children: Vec<u8> = [
        avp(base::AVP_PROXY_HOST, 0x40, b"proxy.private.invalid"),
        avp(base::AVP_PROXY_STATE, 0x40, b"opaque-private-state"),
    ]
    .into_iter()
    .flatten()
    .collect();
    avp(base::AVP_PROXY_INFO, 0x40, &children)
}

fn rar_avps() -> Vec<Vec<u8>> {
    vec![
        avp(base::AVP_SESSION_ID, 0x40, SESSION.as_bytes()),
        avp(base::AVP_ORIGIN_HOST, 0x40, b"aaa.private.invalid"),
        avp(base::AVP_ORIGIN_REALM, 0x40, b"private.invalid"),
        avp(base::AVP_DESTINATION_REALM, 0x40, b"access.private.invalid"),
        avp(base::AVP_DESTINATION_HOST, 0x40, b"epdg.private.invalid"),
        avp(
            base::AVP_AUTH_APPLICATION_ID,
            0x40,
            &swm::APPLICATION_ID.get().to_be_bytes(),
        ),
        avp(base::AVP_RE_AUTH_REQUEST_TYPE, 0x40, &0_u32.to_be_bytes()),
        avp(base::AVP_USER_NAME, 0x40, USER.as_bytes()),
        proxy_info(),
        avp(base::AVP_ROUTE_RECORD, 0x40, b"route.private.invalid"),
        avp(AvpCode::new(UNKNOWN), 0x00, b"private-rar-extension"),
    ]
}

fn rar_wire(flags: u8) -> Vec<u8> {
    message(258, flags, HOP_RAR, END_RAR, rar_avps())
}

fn raa_avps() -> Vec<Vec<u8>> {
    vec![
        avp(base::AVP_SESSION_ID, 0x40, SESSION.as_bytes()),
        avp(
            base::AVP_RESULT_CODE,
            0x40,
            &base::RESULT_CODE_DIAMETER_SUCCESS.to_be_bytes(),
        ),
        avp(base::AVP_ORIGIN_HOST, 0x40, b"epdg.private.invalid"),
        avp(base::AVP_ORIGIN_REALM, 0x40, b"access.private.invalid"),
        avp(base::AVP_USER_NAME, 0x40, USER.as_bytes()),
        avp(AvpCode::new(UNKNOWN + 1), 0x00, b"private-raa-extension"),
        proxy_info(),
    ]
}

fn raa_wire() -> Vec<u8> {
    message(258, 0x40, HOP_RAR, END_RAR, raa_avps())
}

fn aar_avps() -> Vec<Vec<u8>> {
    vec![
        avp(base::AVP_SESSION_ID, 0x40, SESSION.as_bytes()),
        avp(
            base::AVP_AUTH_APPLICATION_ID,
            0x40,
            &swm::APPLICATION_ID.get().to_be_bytes(),
        ),
        avp(base::AVP_ORIGIN_HOST, 0x40, b"epdg.private.invalid"),
        avp(base::AVP_ORIGIN_REALM, 0x40, b"private.invalid"),
        avp(base::AVP_DESTINATION_REALM, 0x40, b"aaa.private.invalid"),
        avp(base::AVP_DESTINATION_HOST, 0x40, b"dra.private.invalid"),
        avp(swm::AVP_AUTH_REQUEST_TYPE, 0x40, &2_u32.to_be_bytes()),
        avp(base::AVP_USER_NAME, 0x40, USER.as_bytes()),
        vendor_avp(swm::AVP_AAR_FLAGS, 0x00, &0xffff_ffff_u32.to_be_bytes()),
        vendor_avp(
            swm::AVP_UE_LOCAL_IP_ADDRESS,
            0x00,
            &[0, 1, 198, 51, 100, 10],
        ),
        vendor_avp(
            swm::AVP_HIGH_PRIORITY_ACCESS_INFO,
            0x00,
            &0xffff_ffff_u32.to_be_bytes(),
        ),
        proxy_info(),
        avp(base::AVP_ROUTE_RECORD, 0x40, b"route.private.invalid"),
        avp(AvpCode::new(UNKNOWN), 0x00, b"private-aar-extension"),
    ]
}

fn aar_wire(flags: u8) -> Vec<u8> {
    message(265, flags, HOP_AAR, END_AAR, aar_avps())
}

fn apn_configuration_with(context_identifier: u32, service_selection: &[u8]) -> Vec<u8> {
    let children: Vec<u8> = [
        vendor_avp(
            swm::AVP_CONTEXT_IDENTIFIER,
            0x40,
            &context_identifier.to_be_bytes(),
        ),
        vendor_avp(swm::AVP_PDN_TYPE, 0x40, &2_u32.to_be_bytes()),
        avp(swm::AVP_SERVICE_SELECTION, 0x40, service_selection),
    ]
    .into_iter()
    .flatten()
    .collect();
    vendor_avp(swm::AVP_APN_CONFIGURATION, 0x40, &children)
}

fn apn_configuration() -> Vec<u8> {
    apn_configuration_with(7, b"ims")
}

fn aaa_avps() -> Vec<Vec<u8>> {
    vec![
        avp(base::AVP_SESSION_ID, 0x40, SESSION.as_bytes()),
        avp(
            base::AVP_AUTH_APPLICATION_ID,
            0x40,
            &swm::APPLICATION_ID.get().to_be_bytes(),
        ),
        avp(swm::AVP_AUTH_REQUEST_TYPE, 0x40, &2_u32.to_be_bytes()),
        avp(
            base::AVP_RESULT_CODE,
            0x40,
            &base::RESULT_CODE_DIAMETER_SUCCESS.to_be_bytes(),
        ),
        avp(base::AVP_ORIGIN_HOST, 0x40, b"dra.private.invalid"),
        avp(base::AVP_ORIGIN_REALM, 0x40, b"aaa.private.invalid"),
        avp(base::AVP_USER_NAME, 0x40, USER.as_bytes()),
        apn_configuration(),
        avp(AvpCode::new(UNKNOWN + 1), 0x00, b"private-aaa-extension"),
        proxy_info(),
    ]
}

fn aaa_wire() -> Vec<u8> {
    message(265, 0x40, HOP_AAR, END_AAR, aaa_avps())
}

#[derive(Debug, Clone, Copy)]
enum AuthorizationFixture {
    Rar,
    Raa,
    Aar,
    Aaa,
}

const AUTHORIZATION_FIXTURES: [AuthorizationFixture; 4] = [
    AuthorizationFixture::Rar,
    AuthorizationFixture::Raa,
    AuthorizationFixture::Aar,
    AuthorizationFixture::Aaa,
];

impl AuthorizationFixture {
    const fn label(self) -> &'static str {
        match self {
            Self::Rar => "RAR",
            Self::Raa => "RAA",
            Self::Aar => "AAR",
            Self::Aaa => "AAA",
        }
    }

    const fn command(self) -> u32 {
        match self {
            Self::Rar | Self::Raa => 258,
            Self::Aar | Self::Aaa => 265,
        }
    }

    const fn flags(self) -> u8 {
        match self {
            Self::Rar | Self::Aar => 0xc0,
            Self::Raa | Self::Aaa => 0x40,
        }
    }

    const fn identifiers(self) -> (u32, u32) {
        match self {
            Self::Rar | Self::Raa => (HOP_RAR, END_RAR),
            Self::Aar | Self::Aaa => (HOP_AAR, END_AAR),
        }
    }

    fn avps(self) -> Vec<Vec<u8>> {
        match self {
            Self::Rar => rar_avps(),
            Self::Raa => raa_avps(),
            Self::Aar => aar_avps(),
            Self::Aaa => aaa_avps(),
        }
    }

    fn wire(self, avps: Vec<Vec<u8>>) -> Vec<u8> {
        let (hop, end) = self.identifiers();
        message(self.command(), self.flags(), hop, end, avps)
    }

    fn parse(self, wire: &[u8], ctx: DecodeContext) -> Result<(), DecodeError> {
        let message = decode(wire);
        match self {
            Self::Rar => swm::parse_swm_re_auth_request(&message, ctx).map(|_| ()),
            Self::Raa => swm::parse_swm_re_auth_answer(&message, ctx).map(|_| ()),
            Self::Aar => swm::parse_swm_authorization_request(&message, ctx).map(|_| ()),
            Self::Aaa => swm::parse_swm_authorization_answer(&message, ctx).map(|_| ()),
        }
    }
}

fn avp_code(raw: &[u8]) -> u32 {
    u32::from_be_bytes(raw[0..4].try_into().expect("fixture AVP has a code"))
}

fn replace_first_avp(avps: &mut [Vec<u8>], code: AvpCode, replacement: Vec<u8>) {
    let entry = avps
        .iter_mut()
        .find(|raw| avp_code(raw) == code.get())
        .expect("fixture contains the AVP being mutated");
    *entry = replacement;
}

fn assert_bounded_rejection(
    fixture: AuthorizationFixture,
    class: &str,
    wire: &[u8],
    ctx: DecodeContext,
) -> DecodeError {
    let error = match fixture.parse(wire, ctx) {
        Ok(()) => panic!("{} must reject {class}", fixture.label()),
        Err(error) => error,
    };
    assert!(
        error.offset() <= wire.len(),
        "{} {class} offset {} exceeds wire length {}",
        fixture.label(),
        error.offset(),
        wire.len()
    );
    error
}

fn decode(wire: &[u8]) -> Message<'_> {
    let (tail, message) = Message::decode(wire, DecodeContext::default())
        .expect("hand-authored Diameter fixture must frame");
    assert!(tail.is_empty());
    message
}

fn encode(message: &OwnedMessage) -> Vec<u8> {
    let mut wire = BytesMut::new();
    message
        .encode(&mut wire, EncodeContext::default())
        .expect("typed message must encode");
    wire.to_vec()
}

fn expected_re_auth_peer(connection: SwmDiameterConnectionToken) -> SwmExpectedAnswerPeer {
    SwmExpectedAnswerPeer::direct(connection, "epdg.private.invalid", "access.private.invalid")
}

fn expected_authorization_peer(connection: SwmDiameterConnectionToken) -> SwmExpectedAnswerPeer {
    SwmExpectedAnswerPeer::routed(connection)
}

fn parsed_re_auth_request(wire: &[u8]) -> SwmReAuthRequestEnvelope {
    swm::parse_swm_re_auth_request_envelope(&decode(wire), DecodeContext::default())
        .expect("valid RAR must parse")
        .with_expected_answer_peer(expected_re_auth_peer(CONNECTION_A))
}

fn parsed_authorization_request(wire: &[u8]) -> swm::SwmAuthorizationRequestEnvelope {
    swm::parse_swm_authorization_request_envelope(&decode(wire), DecodeContext::default())
        .expect("valid AAR must parse")
        .with_expected_answer_peer(expected_authorization_peer(CONNECTION_A))
}

fn parsed_re_auth_answer(
    message: &Message<'_>,
    connection: SwmDiameterConnectionToken,
) -> swm::SwmReAuthAnswerEnvelope {
    swm::parse_swm_re_auth_answer_envelope_from_connection(
        message,
        connection,
        DecodeContext::default(),
    )
    .expect("valid RAA must parse")
}

fn parsed_authorization_answer(
    message: &Message<'_>,
    connection: SwmDiameterConnectionToken,
) -> swm::SwmAuthorizationAnswerEnvelope {
    swm::parse_swm_authorization_answer_envelope_from_connection(
        message,
        connection,
        DecodeContext::default(),
    )
    .expect("valid AAA must parse")
}

#[test]
fn rar_fixture_round_trips_and_retains_t() {
    for flags in [0xc0, 0xd0] {
        let wire = rar_wire(flags);
        let envelope = parsed_re_auth_request(&wire);
        assert_eq!(envelope.request().session_id.as_ref(), SESSION);
        assert_eq!(envelope.request().user_name.as_ref(), USER);
        assert_eq!(
            envelope.request().re_auth_request_type,
            SwmReAuthRequestType::AuthorizeOnly
        );
        assert_eq!(envelope.proxy_info_count(), 1);
        assert_eq!(envelope.is_potentially_retransmitted(), flags & 0x10 != 0);
        let rebuilt = swm::build_swm_re_auth_request(&envelope, EncodeContext::default())
            .expect("parsed RAR must rebuild");
        assert_eq!(encode(&rebuilt), wire);
    }
}

#[test]
fn raa_fixture_round_trips_and_correlates() {
    let request = parsed_re_auth_request(&rar_wire(0xc0));
    let answer_wire = raa_wire();
    let answer = parsed_re_auth_answer(&decode(&answer_wire), CONNECTION_A);
    assert_eq!(answer.answer().result, SwmReAuthResult::Success);
    let rebuilt =
        swm::build_swm_re_auth_answer(&request, answer.answer(), EncodeContext::default())
            .expect("parsed RAA must rebuild");
    assert_eq!(encode(&rebuilt), answer_wire);
    request
        .correlate_answer(answer)
        .expect("exact RAR/RAA must correlate");
}

#[test]
fn correlation_rejects_a_changed_proxy_chain() {
    let request = parsed_re_auth_request(&rar_wire(0xc0));
    let mut answer_avps = vec![
        avp(base::AVP_SESSION_ID, 0x40, SESSION.as_bytes()),
        avp(
            base::AVP_RESULT_CODE,
            0x40,
            &base::RESULT_CODE_DIAMETER_SUCCESS.to_be_bytes(),
        ),
        avp(base::AVP_ORIGIN_HOST, 0x40, b"epdg.private.invalid"),
        avp(base::AVP_ORIGIN_REALM, 0x40, b"access.private.invalid"),
        avp(base::AVP_USER_NAME, 0x40, USER.as_bytes()),
    ];
    let changed_children: Vec<u8> = [
        avp(base::AVP_PROXY_HOST, 0x40, b"proxy.private.invalid"),
        avp(base::AVP_PROXY_STATE, 0x40, b"changed-private-state"),
    ]
    .into_iter()
    .flatten()
    .collect();
    answer_avps.push(avp(base::AVP_PROXY_INFO, 0x40, &changed_children));
    let wire = message(258, 0x40, HOP_RAR, END_RAR, answer_avps);
    let answer = parsed_re_auth_answer(&decode(&wire), CONNECTION_A);
    let error = request
        .correlate_answer(answer)
        .expect_err("changed Proxy-State must not correlate");
    assert_eq!(error.as_str(), "swm_authorization_proxy_info_mismatch");
}

#[test]
fn aar_fixture_round_trips_with_typed_vendor_values() {
    let wire = aar_wire(0xc0);
    let envelope = parsed_authorization_request(&wire);
    let request = envelope.request();
    assert_eq!(request.auth_request_type, AuthRequestType::AuthorizeOnly);
    assert_eq!(
        request.aar_flags,
        Some(SwmAarFlags::wlan_location_info_request())
    );
    assert_eq!(
        request.ue_local_ip_address,
        Some(IpAddr::V4(Ipv4Addr::new(198, 51, 100, 10)))
    );
    assert_eq!(
        request.high_priority_access_info,
        Some(SwmHighPriorityAccessInfo::configured())
    );
    let rebuilt = swm::build_swm_authorization_request(&envelope, EncodeContext::default())
        .expect("parsed AAR must rebuild canonically");
    let rebuilt_wire = encode(&rebuilt);
    assert_eq!(rebuilt_wire[4] & 0x10, 0);
    assert_ne!(
        rebuilt_wire, wire,
        "undefined vendor flag bits are canonicalized"
    );
    let mut retry = envelope.clone();
    retry.mark_for_failover_retransmission(HOP_FAILOVER, expected_authorization_peer(CONNECTION_B));
    let retry_wire = encode(
        &swm::build_swm_authorization_request(&retry, EncodeContext::default())
            .expect("AAR retry must build"),
    );
    assert_eq!(retry_wire[4] & 0x10, 0x10);
    assert_eq!(&retry_wire[5..12], &rebuilt_wire[5..12]);
    assert_eq!(&retry_wire[16..], &rebuilt_wire[16..]);
    assert_eq!(&retry_wire[12..16], &HOP_FAILOVER.to_be_bytes());
}

#[test]
fn understood_table_avps_ignore_received_m_mismatch_and_encode_canonically() {
    let mut avps = aar_avps();
    for raw in &mut avps {
        let code = u32::from_be_bytes(raw[0..4].try_into().expect("fixed AVP code"));
        if code == swm::AVP_AAR_FLAGS.get()
            || code == swm::AVP_UE_LOCAL_IP_ADDRESS.get()
            || code == swm::AVP_HIGH_PRIORITY_ACCESS_INFO.get()
        {
            raw[4] |= 0x40;
        }
    }
    avps.insert(1, avp(swm::AVP_DRMP, 0x40, &3_u32.to_be_bytes()));
    let wire = message(265, 0xc0, HOP_AAR, END_AAR, avps);
    let envelope = parsed_authorization_request(&wire);
    let canonical = encode(
        &swm::build_swm_authorization_request(&envelope, EncodeContext::default())
            .expect("typed rebuild must canonicalize flags"),
    );
    let message = decode(&canonical);
    let mut remaining = message.raw_avps;
    while !remaining.is_empty() {
        let (tail, parsed) =
            opc_proto_diameter::RawAvp::decode(remaining, DecodeContext::default())
                .expect("rebuilt AVP must frame");
        if matches!(
            parsed.header.code,
            code if code == swm::AVP_AAR_FLAGS
                || code == swm::AVP_UE_LOCAL_IP_ADDRESS
                || code == swm::AVP_HIGH_PRIORITY_ACCESS_INFO
                || code == swm::AVP_DRMP
        ) {
            assert!(!parsed.header.flags.is_mandatory());
        }
        remaining = tail;
    }
}

#[test]
fn received_load_m_mismatch_is_tolerated_and_reemitted_canonically() {
    let load_children: Vec<u8> = [
        avp(swm::AVP_LOAD_TYPE, 0x00, &0_u32.to_be_bytes()),
        avp(swm::AVP_LOAD_VALUE, 0x00, &42_u64.to_be_bytes()),
        avp(swm::AVP_SOURCE_ID, 0x00, b"source-private-invalid"),
    ]
    .into_iter()
    .flatten()
    .collect();
    let mut avps = aaa_wire();
    let load = avp(swm::AVP_LOAD, 0x40, &load_children);
    let old_len = avps.len();
    avps.extend_from_slice(&load);
    let new_len = avps.len();
    avps[1..4].copy_from_slice(&(new_len as u32).to_be_bytes()[1..]);
    assert!(new_len > old_len);
    let answer = swm::parse_swm_authorization_answer(&decode(&avps), DecodeContext::default())
        .expect("understood Load must ignore the received M mismatch");
    let rebuilt = encode(
        &swm::build_swm_authorization_answer(
            &parsed_authorization_request(&aar_wire(0xc0)),
            &answer,
            EncodeContext::default(),
        )
        .expect("the encode boundary must normalize a received Load M mismatch"),
    );
    let rebuilt_message = decode(&rebuilt);
    let rebuilt_load = rebuilt_message
        .avps(DecodeContext::default())
        .find_map(|avp| {
            let avp = avp.expect("rebuilt AVP framing");
            (avp.header.code == swm::AVP_LOAD).then_some(avp)
        })
        .expect("rebuilt AAA must contain Load");
    assert!(!rebuilt_load.header.flags.is_mandatory());
}

#[test]
fn aaa_accepts_exactly_one_typed_experimental_result() {
    let grouped: Vec<u8> = [
        avp(
            base::AVP_VENDOR_ID,
            0x40,
            &VENDOR_ID_3GPP.get().to_be_bytes(),
        ),
        avp(
            base::AVP_EXPERIMENTAL_RESULT_CODE,
            0x40,
            &5_001_u32.to_be_bytes(),
        ),
    ]
    .into_iter()
    .flatten()
    .collect();
    let wire = message(
        265,
        0x40,
        HOP_AAR,
        END_AAR,
        vec![
            avp(base::AVP_SESSION_ID, 0x40, SESSION.as_bytes()),
            avp(
                base::AVP_AUTH_APPLICATION_ID,
                0x40,
                &swm::APPLICATION_ID.get().to_be_bytes(),
            ),
            avp(swm::AVP_AUTH_REQUEST_TYPE, 0x40, &2_u32.to_be_bytes()),
            avp(base::AVP_EXPERIMENTAL_RESULT, 0x40, &grouped),
            avp(base::AVP_ORIGIN_HOST, 0x40, b"aaa.private.invalid"),
            avp(base::AVP_ORIGIN_REALM, 0x40, b"private.invalid"),
            avp(base::AVP_USER_NAME, 0x40, USER.as_bytes()),
        ],
    );
    let answer = swm::parse_swm_authorization_answer(&decode(&wire), DecodeContext::default())
        .expect("experimental result AAA must parse");
    assert_eq!(
        answer.result,
        SwmDiameterResult::Experimental {
            vendor_id: VENDOR_ID_3GPP,
            code: 5_001,
        }
    );
}

#[test]
fn originated_aaa_rejects_experimental_protocol_error_class() {
    let request = parsed_authorization_request(&aar_wire(0xc0));
    let answer = swm::SwmAuthorizationAnswer::for_request(
        &request,
        SwmDiameterResult::Experimental {
            vendor_id: VENDOR_ID_3GPP,
            code: 3_001,
        },
        "aaa.private.invalid",
        "private.invalid",
    );
    swm::build_swm_authorization_answer(&request, &answer, EncodeContext::default())
        .expect_err("experimental 3xxx cannot satisfy RFC 6733 generic E-bit grammar");

    let answer = swm::SwmAuthorizationAnswer::for_request(
        &request,
        SwmDiameterResult::Experimental {
            vendor_id: VENDOR_ID_3GPP,
            code: 5_001,
        },
        "aaa.private.invalid",
        "private.invalid",
    );
    let built = swm::build_swm_authorization_answer(&request, &answer, EncodeContext::default())
        .expect("ordinary experimental application result remains encodable");
    assert!(!built.header.flags.is_error());
    let parsed =
        swm::parse_swm_authorization_answer(&decode(&encode(&built)), DecodeContext::default())
            .expect("originated experimental application result must self-parse");
    assert_eq!(parsed.result, answer.result);
}

#[test]
fn raa_origin_is_explicit_local_identity_not_request_destination() {
    let request = parsed_re_auth_request(&rar_wire(0xc0));
    let answer = SwmReAuthAnswer::for_request(
        &request,
        SwmReAuthResult::Success,
        "configured-local.private.invalid",
        "configured-realm.invalid",
    );
    assert_ne!(
        answer.origin_host.as_ref(),
        request.request().destination_host.as_ref()
    );
    assert_ne!(
        answer.origin_realm.as_ref(),
        request.request().destination_realm.as_ref()
    );

    let built = swm::build_swm_re_auth_answer(&request, &answer, EncodeContext::default())
        .expect("request-bound RAA accepts an explicitly configured local Origin");
    let parsed = swm::parse_swm_re_auth_answer(&decode(&encode(&built)), DecodeContext::default())
        .expect("explicit-origin RAA must parse");
    assert_eq!(
        parsed.origin_host.as_ref(),
        "configured-local.private.invalid"
    );
    assert_eq!(parsed.origin_realm.as_ref(), "configured-realm.invalid");
}

#[test]
fn code_collisions_are_vendor_aware_while_malformed_roles_and_headers_fail_closed() {
    let mut ietf_collision = aar_avps();
    let index = ietf_collision
        .iter()
        .position(|raw| {
            u32::from_be_bytes(raw[0..4].try_into().expect("fixed code"))
                == swm::AVP_AAR_FLAGS.get()
        })
        .expect("AAR-Flags fixture");
    ietf_collision[index] = avp(swm::AVP_AAR_FLAGS, 0x00, &1_u32.to_be_bytes());
    let wire = message(265, 0xc0, HOP_AAR, END_AAR, ietf_collision);
    let parsed = swm::parse_swm_authorization_request(&decode(&wire), DecodeContext::default())
        .expect("an unassigned IETF key must not alias the 3GPP AAR-Flags key");
    assert!(parsed.aar_flags.is_none());
    assert!(parsed
        .additional_avps
        .iter()
        .any(|avp| avp.code() == swm::AVP_AAR_FLAGS && avp.vendor_id().is_none()));

    let mut wrong_length = rar_avps();
    let index = wrong_length
        .iter()
        .position(|raw| {
            u32::from_be_bytes(raw[0..4].try_into().expect("fixed code"))
                == base::AVP_RE_AUTH_REQUEST_TYPE.get()
        })
        .expect("Re-Auth-Request-Type fixture");
    wrong_length[index] = avp(base::AVP_RE_AUTH_REQUEST_TYPE, 0x40, &[0, 0, 0]);
    let wire = message(258, 0xc0, HOP_RAR, END_RAR, wrong_length);
    assert!(swm::parse_swm_re_auth_request(&decode(&wire), DecodeContext::default()).is_err());

    let mut wrong_role = rar_avps();
    wrong_role.push(avp(base::AVP_RESULT_CODE, 0x40, &2_001_u32.to_be_bytes()));
    let wire = message(258, 0xc0, HOP_RAR, END_RAR, wrong_role);
    assert!(swm::parse_swm_re_auth_request(&decode(&wire), DecodeContext::default()).is_err());

    let wire = message(265, 0xc0, HOP_AAR, END_AAR, vec![]);
    assert!(swm::parse_swm_authorization_answer(&decode(&wire), DecodeContext::default()).is_err());

    let wire = message(
        258,
        0x60,
        HOP_RAR,
        END_RAR,
        vec![
            avp(base::AVP_SESSION_ID, 0x40, SESSION.as_bytes()),
            avp(base::AVP_RESULT_CODE, 0x40, &3_002_u32.to_be_bytes()),
            avp(base::AVP_ORIGIN_HOST, 0x40, b"epdg.private.invalid"),
            avp(base::AVP_ORIGIN_REALM, 0x40, b"private.invalid"),
            avp(base::AVP_USER_NAME, 0x40, USER.as_bytes()),
        ],
    );
    assert_eq!(
        swm::parse_swm_re_auth_answer(&decode(&wire), DecodeContext::default())
            .expect("generic protocol result must remain receive-side visible")
            .result,
        SwmReAuthResult::Other(3_002)
    );
}

#[test]
fn generic_e_bit_errors_accept_minimal_ccf_and_correlate_safely() {
    let re_auth_request = parsed_re_auth_request(&rar_wire(0xc0));
    let generic_raa = message(
        258,
        0x60,
        HOP_RAR,
        END_RAR,
        vec![
            avp(base::AVP_RESULT_CODE, 0x40, &3_002_u32.to_be_bytes()),
            avp(base::AVP_ORIGIN_HOST, 0x40, b"agent.private.invalid"),
            avp(base::AVP_ORIGIN_REALM, 0x40, b"agent.invalid"),
            proxy_info(),
        ],
    );
    let generic_raa = parsed_re_auth_answer(&decode(&generic_raa), CONNECTION_A);
    assert!(generic_raa.uses_generic_error_grammar());
    assert_eq!(generic_raa.answer().result, SwmReAuthResult::Other(3_002));
    assert!(generic_raa.answer().session_id.is_none());
    assert!(generic_raa.answer().user_name.is_none());
    re_auth_request
        .correlate_answer(generic_raa)
        .expect("agent error correlates by connection, transaction, P, and Proxy-Info");

    let authorization_request = parsed_authorization_request(&aar_wire(0xc0));
    let experimental_children: Vec<u8> = [
        avp(
            base::AVP_VENDOR_ID,
            0x40,
            &VENDOR_ID_3GPP.get().to_be_bytes(),
        ),
        avp(
            base::AVP_EXPERIMENTAL_RESULT_CODE,
            0x40,
            &5_005_u32.to_be_bytes(),
        ),
    ]
    .into_iter()
    .flatten()
    .collect();
    let generic_aaa = message(
        265,
        0x60,
        HOP_AAR,
        END_AAR,
        vec![
            avp(
                base::AVP_RESULT_CODE,
                0x40,
                &base::RESULT_CODE_DIAMETER_MISSING_AVP.to_be_bytes(),
            ),
            avp(base::AVP_ORIGIN_HOST, 0x40, b"agent.private.invalid"),
            avp(base::AVP_ORIGIN_REALM, 0x40, b"agent.invalid"),
            avp(base::AVP_EXPERIMENTAL_RESULT, 0x40, &experimental_children),
            proxy_info(),
        ],
    );
    let generic_aaa = parsed_authorization_answer(&decode(&generic_aaa), CONNECTION_A);
    assert!(generic_aaa.uses_generic_error_grammar());
    assert_eq!(
        generic_aaa.answer().result,
        SwmDiameterResult::Base(base::RESULT_CODE_DIAMETER_MISSING_AVP)
    );
    assert!(generic_aaa.answer().session_id.is_none());
    assert!(generic_aaa.answer().auth_request_type.is_none());
    assert!(generic_aaa.answer().user_name.is_none());
    assert_eq!(generic_aaa.answer().additional_avps.len(), 1);
    authorization_request
        .correlate_answer(generic_aaa)
        .expect("agent error is exempt only from logical-Origin correlation");

    let experimental_only = message(
        265,
        0x60,
        HOP_AAR,
        END_AAR,
        vec![
            avp(base::AVP_ORIGIN_HOST, 0x40, b"agent.private.invalid"),
            avp(base::AVP_ORIGIN_REALM, 0x40, b"agent.invalid"),
            avp(base::AVP_EXPERIMENTAL_RESULT, 0x40, &experimental_children),
        ],
    );
    assert!(
        swm::parse_swm_authorization_answer(&decode(&experimental_only), DecodeContext::default())
            .is_err(),
        "generic E-bit grammar requires base Result-Code"
    );
}

#[test]
fn ordinary_answers_apply_explicit_direct_or_routed_peer_policy() {
    let re_auth_request = parsed_re_auth_request(&rar_wire(0xc0));
    let wrong_host_raa = message(
        258,
        0x40,
        HOP_RAR,
        END_RAR,
        vec![
            avp(base::AVP_SESSION_ID, 0x40, SESSION.as_bytes()),
            avp(
                base::AVP_RESULT_CODE,
                0x40,
                &base::RESULT_CODE_DIAMETER_SUCCESS.to_be_bytes(),
            ),
            avp(base::AVP_ORIGIN_HOST, 0x40, b"evil.private.invalid"),
            avp(base::AVP_ORIGIN_REALM, 0x40, b"access.private.invalid"),
            avp(base::AVP_USER_NAME, 0x40, USER.as_bytes()),
            proxy_info(),
        ],
    );
    let wrong_host_raa = parsed_re_auth_answer(&decode(&wrong_host_raa), CONNECTION_A);
    assert_eq!(
        re_auth_request
            .clone()
            .correlate_answer(wrong_host_raa)
            .expect_err("direct RAA must satisfy the trusted logical-Origin policy"),
        swm::SwmAuthorizationCorrelationError::PeerIdentityMismatch
    );

    let wrong_realm_raa = message(
        258,
        0x40,
        HOP_RAR,
        END_RAR,
        vec![
            avp(base::AVP_SESSION_ID, 0x40, SESSION.as_bytes()),
            avp(
                base::AVP_RESULT_CODE,
                0x40,
                &base::RESULT_CODE_DIAMETER_SUCCESS.to_be_bytes(),
            ),
            avp(base::AVP_ORIGIN_HOST, 0x40, b"epdg.private.invalid"),
            avp(base::AVP_ORIGIN_REALM, 0x40, b"rogue.private.invalid"),
            avp(base::AVP_USER_NAME, 0x40, USER.as_bytes()),
            proxy_info(),
        ],
    );
    let wrong_realm_raa = parsed_re_auth_answer(&decode(&wrong_realm_raa), CONNECTION_A);
    assert_eq!(
        re_auth_request
            .correlate_answer(wrong_realm_raa)
            .expect_err("direct RAA realm must satisfy the trusted logical-Origin policy"),
        swm::SwmAuthorizationCorrelationError::PeerIdentityMismatch
    );

    let mut final_server_aaa = aaa_wire();
    let expected = b"dra.private.invalid";
    let replacement = b"aaa.private.invalid";
    assert_eq!(expected.len(), replacement.len());
    let position = final_server_aaa
        .windows(expected.len())
        .position(|window| window == expected)
        .expect("AAA Origin-Host must be present");
    final_server_aaa[position..position + replacement.len()].copy_from_slice(replacement);
    parsed_authorization_request(&aar_wire(0xc0))
        .correlate_answer(parsed_authorization_answer(
            &decode(&final_server_aaa),
            CONNECTION_A,
        ))
        .expect("routed AAR via DRA accepts the final AAA server Origin");

    let direct_request = parsed_authorization_request(&aar_wire(0xc0)).with_expected_answer_peer(
        SwmExpectedAnswerPeer::direct(CONNECTION_A, "dra.private.invalid", "aaa.private.invalid"),
    );
    assert_eq!(
        direct_request
            .correlate_answer(parsed_authorization_answer(
                &decode(&final_server_aaa),
                CONNECTION_A,
            ))
            .expect_err("direct AAR policy must reject a different final Origin-Host"),
        swm::SwmAuthorizationCorrelationError::PeerIdentityMismatch
    );

    let mut wrong_realm_aaa = aaa_wire();
    let expected = b"aaa.private.invalid";
    let replacement = b"bad.private.invalid";
    assert_eq!(expected.len(), replacement.len());
    let position = wrong_realm_aaa
        .windows(expected.len())
        .position(|window| window == expected)
        .expect("AAA Origin-Realm must be present");
    wrong_realm_aaa[position..position + replacement.len()].copy_from_slice(replacement);
    let realm_routed_request =
        parsed_authorization_request(&aar_wire(0xc0)).with_expected_answer_peer(
            SwmExpectedAnswerPeer::routed_in_realm(CONNECTION_A, "aaa.private.invalid"),
        );
    assert_eq!(
        realm_routed_request
            .correlate_answer(parsed_authorization_answer(
                &decode(&wrong_realm_aaa),
                CONNECTION_A,
            ))
            .expect_err("realm-routed AAR must reject an Origin outside its trusted realm"),
        swm::SwmAuthorizationCorrelationError::PeerIdentityMismatch
    );
}

#[test]
fn correlation_requires_binding_and_the_exact_connection_generation() {
    let unbound = swm::parse_swm_authorization_request_envelope(
        &decode(&aar_wire(0xc0)),
        DecodeContext::default(),
    )
    .expect("inbound AAR must parse without manufacturing transport evidence");
    assert!(
        swm::build_swm_authorization_request(&unbound, EncodeContext::default()).is_err(),
        "an unbound AAR cannot be dispatched as an outbound request"
    );
    assert_eq!(
        unbound
            .correlate_answer(parsed_authorization_answer(
                &decode(&aaa_wire()),
                CONNECTION_A,
            ))
            .expect_err("an unbound request must not correlate"),
        swm::SwmAuthorizationCorrelationError::PeerBindingMissing
    );

    let unbound_rar =
        swm::parse_swm_re_auth_request_envelope(&decode(&rar_wire(0xc0)), DecodeContext::default())
            .expect("inbound RAR must parse without manufacturing transport evidence");
    assert!(
        swm::build_swm_re_auth_request(&unbound_rar, EncodeContext::default()).is_err(),
        "an unbound RAR cannot be dispatched as an outbound request"
    );

    assert_eq!(
        parsed_authorization_request(&aar_wire(0xc0))
            .correlate_answer(parsed_authorization_answer(
                &decode(&aaa_wire()),
                CONNECTION_B,
            ))
            .expect_err("a new authenticated connection generation must not satisfy old state"),
        swm::SwmAuthorizationCorrelationError::PeerConnectionMismatch
    );

    let generic_error = message(
        265,
        0x60,
        HOP_AAR,
        END_AAR,
        vec![
            avp(base::AVP_RESULT_CODE, 0x40, &3_002_u32.to_be_bytes()),
            avp(base::AVP_ORIGIN_HOST, 0x40, b"agent.private.invalid"),
            avp(base::AVP_ORIGIN_REALM, 0x40, b"agent.invalid"),
            proxy_info(),
        ],
    );
    assert_eq!(
        parsed_authorization_request(&aar_wire(0xc0))
            .correlate_answer(parsed_authorization_answer(
                &decode(&generic_error),
                CONNECTION_B,
            ))
            .expect_err("generic E-bit errors skip Origin policy, not connection binding"),
        swm::SwmAuthorizationCorrelationError::PeerConnectionMismatch
    );
}

#[test]
fn additional_avp_count_is_bounded_independently_of_decode_context() {
    let mut avps = rar_avps();
    avps.retain(|raw| u32::from_be_bytes(raw[0..4].try_into().expect("fixed code")) != UNKNOWN);
    for code in 100_000..100_129 {
        avps.push(avp(AvpCode::new(code), 0x00, b"bounded-private-extension"));
    }
    let wire = message(258, 0xc0, HOP_RAR, END_RAR, avps);
    let error = swm::parse_swm_re_auth_request(
        &decode(&wire),
        DecodeContext {
            max_ies: 512,
            ..DecodeContext::default()
        },
    )
    .expect_err("129th additional AVP must exceed the typed bound");
    assert_eq!(error.code(), &DecodeErrorCode::IeCountExceeded);
}

#[test]
fn aaa_fixture_has_answer_role_and_correlates() {
    let request = parsed_authorization_request(&aar_wire(0xc0));
    let wire = aaa_wire();
    assert_eq!(
        wire[4] & 0x80,
        0,
        "AAA must clear R despite printed ABNF typo"
    );
    let answer = parsed_authorization_answer(&decode(&wire), CONNECTION_A);
    assert_eq!(answer.answer().result, SwmDiameterResult::Base(2001));
    assert_eq!(
        answer
            .answer()
            .apn_configuration
            .as_ref()
            .expect("typed APN must be present")
            .service_selection
            .as_ref(),
        "ims"
    );
    let rebuilt =
        swm::build_swm_authorization_answer(&request, answer.answer(), EncodeContext::default())
            .expect("parsed AAA must rebuild");
    assert_eq!(encode(&rebuilt), wire);
    request
        .correlate_answer(answer)
        .expect("exact AAR/AAA must correlate");
}

#[test]
fn aaa_rejects_invalid_apn_profile_on_decode_and_encode() {
    let mut invalid_wire = aaa_wire();
    let valid_apn = apn_configuration();
    let position = invalid_wire
        .windows(valid_apn.len())
        .position(|window| window == valid_apn)
        .expect("AAA APN fixture must be present");
    let invalid_apn = apn_configuration_with(0, b"ims");
    invalid_wire[position..position + invalid_apn.len()].copy_from_slice(&invalid_apn);
    assert!(
        swm::parse_swm_authorization_answer(&decode(&invalid_wire), DecodeContext::default())
            .is_err(),
        "zero Context-Identifier must fail closed on decode"
    );

    let request = parsed_authorization_request(&aar_wire(0xc0));
    let mut answer =
        swm::parse_swm_authorization_answer(&decode(&aaa_wire()), DecodeContext::default())
            .expect("valid AAA must parse");
    answer
        .apn_configuration
        .as_mut()
        .expect("typed APN must be present")
        .service_selection = Redacted::from(String::new());
    assert!(
        swm::build_swm_authorization_answer(&request, &answer, EncodeContext::default()).is_err(),
        "empty Service-Selection must fail closed on encode"
    );
}

#[test]
fn missing_request_avps_have_typed_provenance_and_answers_reject_every_missing_field() {
    for missing in [
        base::AVP_SESSION_ID,
        base::AVP_ORIGIN_HOST,
        base::AVP_ORIGIN_REALM,
        base::AVP_DESTINATION_REALM,
        base::AVP_DESTINATION_HOST,
        base::AVP_AUTH_APPLICATION_ID,
        base::AVP_RE_AUTH_REQUEST_TYPE,
        base::AVP_USER_NAME,
    ] {
        let mut avps = rar_avps();
        avps.retain(|raw| {
            u32::from_be_bytes(raw[0..4].try_into().expect("fixed slice")) != missing.get()
        });
        let wire = message(258, 0xc0, HOP_RAR, END_RAR, avps);
        let error = swm::parse_swm_re_auth_request_with_provenance(
            &decode(&wire),
            DecodeContext::default(),
        )
        .expect_err("each missing RAR field must fail");
        let provenance = error.missing_avp().expect("RAR provenance");
        assert_eq!(provenance.avp_code(), missing);
        assert_eq!(provenance.command_code().get(), 258);
    }

    for missing in [
        base::AVP_SESSION_ID,
        base::AVP_AUTH_APPLICATION_ID,
        base::AVP_ORIGIN_HOST,
        base::AVP_ORIGIN_REALM,
        base::AVP_DESTINATION_REALM,
        swm::AVP_AUTH_REQUEST_TYPE,
        base::AVP_USER_NAME,
    ] {
        let mut avps = aar_avps();
        avps.retain(|raw| {
            u32::from_be_bytes(raw[0..4].try_into().expect("fixed slice")) != missing.get()
        });
        let wire = message(265, 0xc0, HOP_AAR, END_AAR, avps);
        let error = swm::parse_swm_authorization_request_with_provenance(
            &decode(&wire),
            DecodeContext::default(),
        )
        .expect_err("each missing AAR field must fail");
        let provenance = error.missing_avp().expect("AAR provenance");
        assert_eq!(provenance.avp_code(), missing);
        assert_eq!(provenance.command_code().get(), 265);
    }

    for missing in [
        base::AVP_SESSION_ID,
        base::AVP_RESULT_CODE,
        base::AVP_ORIGIN_HOST,
        base::AVP_ORIGIN_REALM,
        base::AVP_USER_NAME,
    ] {
        let mut avps = raa_avps();
        avps.retain(|raw| avp_code(raw) != missing.get());
        let wire = AuthorizationFixture::Raa.wire(avps);
        assert_bounded_rejection(
            AuthorizationFixture::Raa,
            "a missing mandatory AVP",
            &wire,
            DecodeContext::default(),
        );
    }

    for missing in [
        base::AVP_SESSION_ID,
        base::AVP_AUTH_APPLICATION_ID,
        swm::AVP_AUTH_REQUEST_TYPE,
        base::AVP_RESULT_CODE,
        base::AVP_ORIGIN_HOST,
        base::AVP_ORIGIN_REALM,
        base::AVP_USER_NAME,
    ] {
        let mut avps = aaa_avps();
        avps.retain(|raw| avp_code(raw) != missing.get());
        let wire = AuthorizationFixture::Aaa.wire(avps);
        assert_bounded_rejection(
            AuthorizationFixture::Aaa,
            "a missing mandatory AVP",
            &wire,
            DecodeContext::default(),
        );
    }
}

#[test]
fn every_authorization_command_rejects_duplicate_wrong_vendor_and_wrong_type_avps() {
    for fixture in AUTHORIZATION_FIXTURES {
        let mut duplicate = fixture.avps();
        let expected_offset = DIAMETER_HEADER_LEN + duplicate.iter().map(Vec::len).sum::<usize>();
        duplicate.push(avp(
            base::AVP_ORIGIN_HOST,
            0x40,
            b"duplicate.private.invalid",
        ));
        let wire = fixture.wire(duplicate);
        let error = assert_bounded_rejection(
            fixture,
            "a duplicated singleton",
            &wire,
            DecodeContext::default(),
        );
        assert_eq!(error.code(), &DecodeErrorCode::DuplicateIe);
        assert_eq!(error.offset(), expected_offset);

        let mut wrong_vendor = fixture.avps();
        replace_first_avp(
            &mut wrong_vendor,
            base::AVP_ORIGIN_HOST,
            vendor_avp(base::AVP_ORIGIN_HOST, 0x40, b"wrong-vendor.private.invalid"),
        );
        let wire = fixture.wire(wrong_vendor);
        assert_bounded_rejection(
            fixture,
            "a wrong-vendor core AVP",
            &wire,
            DecodeContext::default(),
        );

        let mut wrong_type = fixture.avps();
        replace_first_avp(
            &mut wrong_type,
            base::AVP_ORIGIN_HOST,
            avp(base::AVP_ORIGIN_HOST, 0x40, &[0xff]),
        );
        let wire = fixture.wire(wrong_type);
        assert_bounded_rejection(
            fixture,
            "a wrong-type core AVP value",
            &wire,
            DecodeContext::default(),
        );
    }
}

#[test]
fn every_authorization_command_rejects_wrong_role_and_wrong_application() {
    for fixture in AUTHORIZATION_FIXTURES {
        let mut wrong_role_header = fixture.wire(fixture.avps());
        wrong_role_header[4] ^= 0x80;
        assert_bounded_rejection(
            fixture,
            "the opposite command role",
            &wrong_role_header,
            DecodeContext::default(),
        );

        let mut wrong_role_avps = fixture.avps();
        if fixture.flags() & 0x80 != 0 {
            wrong_role_avps.push(avp(
                base::AVP_RESULT_CODE,
                0x40,
                &base::RESULT_CODE_DIAMETER_SUCCESS.to_be_bytes(),
            ));
        } else {
            wrong_role_avps.push(avp(
                base::AVP_DESTINATION_REALM,
                0x40,
                b"request-only.private.invalid",
            ));
        }
        let wire = fixture.wire(wrong_role_avps);
        assert_bounded_rejection(fixture, "a wrong-role AVP", &wire, DecodeContext::default());

        let mut wrong_application = fixture.wire(fixture.avps());
        let other_application = swm::APPLICATION_ID.get().saturating_add(1);
        wrong_application[8..12].copy_from_slice(&other_application.to_be_bytes());
        assert_bounded_rejection(
            fixture,
            "a wrong application id",
            &wrong_application,
            DecodeContext::default(),
        );
    }
}

#[test]
fn command_metadata_drives_supported_authorization_role_and_cardinality() {
    let dictionary = swm::dictionary();
    let command = |code, kind| {
        dictionary
            .find_command(swm::APPLICATION_ID, code, kind)
            .expect("authorization command definition must exist")
    };
    let rar = command(swm::COMMAND_RE_AUTH, CommandKind::Request);
    let raa = command(swm::COMMAND_RE_AUTH, CommandKind::Answer);
    let aar = command(swm::COMMAND_AA, CommandKind::Request);
    let aaa = command(swm::COMMAND_AA, CommandKind::Answer);

    assert!(rar.allows_multiple(AvpKey::ietf(base::AVP_CLASS)));
    assert!(raa.allows_multiple(AvpKey::ietf(base::AVP_CLASS)));
    assert!(raa.allows_multiple(AvpKey::ietf(base::AVP_FAILED_AVP)));
    assert!(raa.allows_multiple(AvpKey::ietf(swm::AVP_REPLY_MESSAGE)));
    assert!(aaa.allows_multiple(AvpKey::ietf(base::AVP_CLASS)));
    assert!(aaa.allows_multiple(AvpKey::ietf(base::AVP_FAILED_AVP)));
    assert!(aaa.allows_multiple(AvpKey::ietf(swm::AVP_REPLY_MESSAGE)));
    assert!(!aar.allows_multiple(AvpKey::ietf(base::AVP_CLASS)));
    assert!(aar
        .find_avp_rule(AvpKey::ietf(base::AVP_CLASS))
        .is_some_and(|rule| rule.cardinality().is_forbidden()));
    assert!(rar
        .find_avp_rule(AvpKey::ietf(swm::AVP_REPLY_MESSAGE))
        .is_some_and(|rule| !rule.cardinality().allows_multiple()));
    for command in [rar, raa, aaa] {
        assert!(command
            .find_avp_rule(AvpKey::ietf(base::AVP_RE_AUTH_REQUEST_TYPE))
            .is_some_and(
                |rule| !rule.cardinality().is_forbidden() && !rule.cardinality().allows_multiple()
            ));
    }
    assert!(aar
        .find_avp_rule(AvpKey::ietf(base::AVP_RE_AUTH_REQUEST_TYPE))
        .is_some_and(|rule| rule.cardinality().is_forbidden()));

    for command in [rar, raa, aar, aaa] {
        for key in [
            AvpKey::ietf(base::AVP_TERMINATION_CAUSE),
            AvpKey::ietf(base::AVP_AUTH_SESSION_STATE),
        ] {
            assert!(command
                .find_avp_rule(key)
                .is_some_and(|rule| rule.cardinality().is_forbidden()));
        }
    }

    for command in [rar, aar] {
        for key in [
            AvpKey::ietf(base::AVP_REDIRECT_HOST),
            AvpKey::ietf(base::AVP_REDIRECT_HOST_USAGE),
            AvpKey::ietf(base::AVP_REDIRECT_MAX_CACHE_TIME),
        ] {
            assert!(command
                .find_avp_rule(key)
                .is_some_and(|rule| rule.cardinality().is_forbidden()));
        }
    }
    for command in [raa, aaa] {
        assert!(command.allows_multiple(AvpKey::ietf(base::AVP_REDIRECT_HOST)));
        for key in [
            AvpKey::ietf(base::AVP_REDIRECT_HOST_USAGE),
            AvpKey::ietf(base::AVP_REDIRECT_MAX_CACHE_TIME),
        ] {
            assert!(command
                .find_avp_rule(key)
                .is_some_and(|rule| !rule.cardinality().allows_multiple()));
        }
    }
}

#[test]
fn answer_redirect_cardinality_is_visible_but_typed_context_stays_unsupported() {
    for fixture in [AuthorizationFixture::Raa, AuthorizationFixture::Aaa] {
        let mut avps = fixture.avps();
        replace_first_avp(
            &mut avps,
            base::AVP_RESULT_CODE,
            avp(base::AVP_RESULT_CODE, 0x40, &3_006_u32.to_be_bytes()),
        );
        avps.retain(|raw| avp_code(raw) != swm::AVP_APN_CONFIGURATION.get());
        let proxy_index = avps
            .iter()
            .position(|raw| avp_code(raw) == base::AVP_PROXY_INFO.get())
            .expect("authorization answer fixture has Proxy-Info");
        avps.insert(
            proxy_index,
            avp(
                base::AVP_REDIRECT_HOST,
                0x40,
                b"aaa://redirect-one.example.invalid",
            ),
        );
        avps.insert(
            proxy_index + 1,
            avp(
                base::AVP_REDIRECT_HOST,
                0x40,
                b"aaa://redirect-two.example.invalid;transport=sctp",
            ),
        );
        avps.insert(
            proxy_index + 2,
            avp(base::AVP_REDIRECT_HOST_USAGE, 0x40, &0_u32.to_be_bytes()),
        );
        avps.insert(
            proxy_index + 3,
            avp(
                base::AVP_REDIRECT_MAX_CACHE_TIME,
                0x40,
                &60_u32.to_be_bytes(),
            ),
        );
        let (hop, end) = fixture.identifiers();
        let wire = message(fixture.command(), 0x60, hop, end, avps.clone());
        let (tail, _) = Message::decode_with_dictionary(
            &wire,
            DecodeContext::conservative(),
            apps::APP_DICTIONARIES,
        )
        .expect("RFC 6733 Redirect-Host must remain explicitly repeatable");
        assert!(tail.is_empty());
        assert_bounded_rejection(
            fixture,
            "an unsupported typed redirect result context",
            &wire,
            DecodeContext::default(),
        );

        avps.insert(
            proxy_index + 4,
            avp(base::AVP_REDIRECT_HOST_USAGE, 0x40, &1_u32.to_be_bytes()),
        );
        let error = Message::decode_with_dictionary(
            &message(fixture.command(), 0x60, hop, end, avps),
            DecodeContext::conservative(),
            apps::APP_DICTIONARIES,
        )
        .expect_err("Redirect-Host-Usage must remain singleton");
        assert_eq!(error.code(), &DecodeErrorCode::DuplicateIe);
    }

    let rar = parsed_re_auth_request(&rar_wire(0xc0));
    let mut raa = swm::parse_swm_re_auth_answer(&decode(&raa_wire()), DecodeContext::default())
        .expect("RAA fixture must parse");
    raa.additional_avps.push(
        SwmAdditionalAvp::new(
            AvpHeader::ietf(base::AVP_REDIRECT_HOST, true),
            b"aaa://redirect.example.invalid".to_vec(),
            EncodeContext::default(),
        )
        .expect("valid Redirect-Host is structurally framed"),
    );
    swm::build_swm_re_auth_answer(&rar, &raa, EncodeContext::default())
        .expect_err("typed RAA builder must not originate unsupported redirect context");

    let aar = parsed_authorization_request(&aar_wire(0xc0));
    let mut aaa =
        swm::parse_swm_authorization_answer(&decode(&aaa_wire()), DecodeContext::default())
            .expect("AAA fixture must parse");
    aaa.additional_avps.push(
        SwmAdditionalAvp::new(
            AvpHeader::ietf(base::AVP_REDIRECT_HOST, true),
            b"aaa://redirect.example.invalid".to_vec(),
            EncodeContext::default(),
        )
        .expect("valid Redirect-Host is structurally framed"),
    );
    swm::build_swm_authorization_answer(&aar, &aaa, EncodeContext::default())
        .expect_err("typed AAA builder must not originate unsupported redirect context");
}

#[test]
fn repeated_failed_avps_survive_conservative_raa_and_aaa_rebuilds() {
    let failed = |host: &[u8]| {
        avp(
            base::AVP_FAILED_AVP,
            0x40,
            &avp(base::AVP_ORIGIN_HOST, 0x40, host),
        )
    };
    let ctx = DecodeContext {
        unknown_ie_policy: UnknownIePolicy::Preserve,
        ..DecodeContext::conservative()
    };

    let rar = parsed_re_auth_request(&rar_wire(0xc0));
    let mut raa_avps = raa_avps();
    let proxy = raa_avps.pop().expect("RAA fixture ends in Proxy-Info");
    raa_avps.extend([
        failed(b"first-failed.private.invalid"),
        failed(b"second-failed.private.invalid"),
        proxy,
    ]);
    let raa_wire = AuthorizationFixture::Raa.wire(raa_avps);
    let (tail, raa_message) =
        Message::decode_with_dictionary(&raa_wire, ctx, apps::APP_DICTIONARIES)
            .expect("RAA command metadata must permit repeated Failed-AVP");
    assert!(tail.is_empty());
    let raa = swm::parse_swm_re_auth_answer(&raa_message, ctx)
        .expect("typed RAA must preserve repeated Failed-AVP");
    assert_eq!(
        raa.additional_avps
            .iter()
            .filter(|avp| avp.code() == base::AVP_FAILED_AVP)
            .count(),
        2
    );
    let rebuilt = swm::build_swm_re_auth_answer(&rar, &raa, EncodeContext::default())
        .expect("repeated RAA Failed-AVP values must remain encodable");
    assert_eq!(encode(&rebuilt), raa_wire);

    let aar = parsed_authorization_request(&aar_wire(0xc0));
    let mut aaa_avps = aaa_avps();
    let proxy = aaa_avps.pop().expect("AAA fixture ends in Proxy-Info");
    aaa_avps.extend([
        failed(b"first-failed.private.invalid"),
        failed(b"second-failed.private.invalid"),
        proxy,
    ]);
    let aaa_wire = AuthorizationFixture::Aaa.wire(aaa_avps);
    let (tail, aaa_message) =
        Message::decode_with_dictionary(&aaa_wire, ctx, apps::APP_DICTIONARIES)
            .expect("AAA command metadata must permit repeated Failed-AVP");
    assert!(tail.is_empty());
    let aaa = swm::parse_swm_authorization_answer(&aaa_message, ctx)
        .expect("typed AAA must preserve repeated Failed-AVP");
    assert_eq!(
        aaa.additional_avps
            .iter()
            .filter(|avp| avp.code() == base::AVP_FAILED_AVP)
            .count(),
        2
    );
    let rebuilt = swm::build_swm_authorization_answer(&aar, &aaa, EncodeContext::default())
        .expect("repeated AAA Failed-AVP values must remain encodable");
    assert_eq!(encode(&rebuilt), aaa_wire);
}

#[test]
fn rfc4005_answer_extensions_use_command_specific_cardinality() {
    let augment = |mut avps: Vec<Vec<u8>>| {
        let result_index = avps
            .iter()
            .position(|raw| avp_code(raw) == base::AVP_RESULT_CODE.get())
            .expect("answer fixture contains Result-Code");
        avps.insert(
            result_index + 1,
            avp(base::AVP_RE_AUTH_REQUEST_TYPE, 0x40, &0_u32.to_be_bytes()),
        );
        let proxy = avps.pop().expect("answer fixture ends in Proxy-Info");
        avps.extend([
            avp(swm::AVP_REPLY_MESSAGE, 0x40, b"first-private-prompt"),
            avp(swm::AVP_REPLY_MESSAGE, 0x40, b"second-private-prompt"),
            proxy,
        ]);
        avps
    };
    let ctx = DecodeContext {
        unknown_ie_policy: UnknownIePolicy::Preserve,
        ..DecodeContext::conservative()
    };

    let raa_avps = augment(raa_avps());
    let raa_wire = AuthorizationFixture::Raa.wire(raa_avps.clone());
    let (tail, raa_message) =
        Message::decode_with_dictionary(&raa_wire, ctx, apps::APP_DICTIONARIES)
            .expect("RAA metadata must permit repeated Reply-Message");
    assert!(tail.is_empty());
    let raa = swm::parse_swm_re_auth_answer(&raa_message, ctx)
        .expect("typed RAA must retain RFC 4005 answer extensions");
    assert_eq!(
        raa.additional_avps
            .iter()
            .filter(|avp| avp.code() == swm::AVP_REPLY_MESSAGE)
            .count(),
        2
    );
    assert_eq!(
        raa.re_auth_request_type,
        Some(SwmReAuthRequestType::AuthorizeOnly)
    );
    let rebuilt = swm::build_swm_re_auth_answer(
        &parsed_re_auth_request(&rar_wire(0xc0)),
        &raa,
        EncodeContext::default(),
    )
    .expect("valid RAA extensions must survive typed rebuild");
    assert_eq!(encode(&rebuilt), raa_wire);

    let aaa_avps = augment(aaa_avps());
    let aaa_wire = AuthorizationFixture::Aaa.wire(aaa_avps.clone());
    let (tail, aaa_message) =
        Message::decode_with_dictionary(&aaa_wire, ctx, apps::APP_DICTIONARIES)
            .expect("AAA metadata must permit repeated Reply-Message");
    assert!(tail.is_empty());
    let aaa = swm::parse_swm_authorization_answer(&aaa_message, ctx)
        .expect("typed AAA must retain RFC 4005 answer extensions");
    assert_eq!(
        aaa.additional_avps
            .iter()
            .filter(|avp| avp.code() == swm::AVP_REPLY_MESSAGE)
            .count(),
        2
    );
    assert_eq!(
        aaa.re_auth_request_type,
        Some(SwmReAuthRequestType::AuthorizeOnly)
    );
    let rebuilt = swm::build_swm_authorization_answer(
        &parsed_authorization_request(&aar_wire(0xc0)),
        &aaa,
        EncodeContext::default(),
    )
    .expect("valid AAA extensions must survive typed rebuild");
    assert_eq!(encode(&rebuilt), aaa_wire);

    for (fixture, mut avps) in [
        (AuthorizationFixture::Raa, raa_avps),
        (AuthorizationFixture::Aaa, aaa_avps),
    ] {
        let proxy = avps.pop().expect("answer fixture ends in Proxy-Info");
        avps.push(avp(
            base::AVP_RE_AUTH_REQUEST_TYPE,
            0x40,
            &1_u32.to_be_bytes(),
        ));
        avps.push(proxy);
        let error =
            Message::decode_with_dictionary(&fixture.wire(avps), ctx, apps::APP_DICTIONARIES)
                .expect_err("Re-Auth-Request-Type must remain singleton in an answer");
        assert_eq!(error.code(), &DecodeErrorCode::DuplicateIe);
    }

    for fixture in [AuthorizationFixture::Raa, AuthorizationFixture::Aaa] {
        let mut avps = fixture.avps();
        avps.push(avp(
            base::AVP_RE_AUTH_REQUEST_TYPE,
            0x40,
            &2_u32.to_be_bytes(),
        ));
        let error = assert_bounded_rejection(
            fixture,
            "an unassigned Re-Auth-Request-Type",
            &fixture.wire(avps),
            DecodeContext::default(),
        );
        assert!(matches!(
            error.code(),
            DecodeErrorCode::InvalidEnumValue {
                field: "Re-Auth-Request-Type",
                value: 2
            }
        ));
    }
}

#[test]
fn authorization_timer_fixtures_round_trip_with_typed_values() {
    const AUTHORIZATION_LIFETIME: u32 = 600;
    const AUTH_GRACE_PERIOD: u32 = 60;
    const SESSION_TIMEOUT: u32 = 900;

    let mut raa_avps = raa_avps();
    let result_index = raa_avps
        .iter()
        .position(|raw| avp_code(raw) == base::AVP_RESULT_CODE.get())
        .expect("RAA fixture contains Result-Code");
    raa_avps.splice(
        result_index + 1..result_index + 1,
        [
            avp(base::AVP_RE_AUTH_REQUEST_TYPE, 0x40, &0_u32.to_be_bytes()),
            avp(
                base::AVP_AUTHORIZATION_LIFETIME,
                0x40,
                &AUTHORIZATION_LIFETIME.to_be_bytes(),
            ),
            avp(
                base::AVP_AUTH_GRACE_PERIOD,
                0x40,
                &AUTH_GRACE_PERIOD.to_be_bytes(),
            ),
        ],
    );
    let raa_wire = AuthorizationFixture::Raa.wire(raa_avps);
    let raa = swm::parse_swm_re_auth_answer(&decode(&raa_wire), DecodeContext::default())
        .expect("hand-authored RAA authorization timers must parse");
    assert_eq!(raa.authorization_lifetime, Some(AUTHORIZATION_LIFETIME));
    assert_eq!(raa.auth_grace_period, Some(AUTH_GRACE_PERIOD));
    assert_eq!(raa.session_id.as_deref().map(String::as_str), Some(SESSION));
    let rebuilt = swm::build_swm_re_auth_answer(
        &parsed_re_auth_request(&rar_wire(0xc0)),
        &raa,
        EncodeContext::default(),
    )
    .expect("typed RAA authorization timers must rebuild");
    assert_eq!(encode(&rebuilt), raa_wire);

    let aar_avps = vec![
        avp(base::AVP_SESSION_ID, 0x40, SESSION.as_bytes()),
        avp(
            base::AVP_AUTH_APPLICATION_ID,
            0x40,
            &swm::APPLICATION_ID.get().to_be_bytes(),
        ),
        avp(base::AVP_ORIGIN_HOST, 0x40, b"epdg.private.invalid"),
        avp(base::AVP_ORIGIN_REALM, 0x40, b"private.invalid"),
        avp(base::AVP_DESTINATION_REALM, 0x40, b"aaa.private.invalid"),
        avp(base::AVP_DESTINATION_HOST, 0x40, b"dra.private.invalid"),
        avp(swm::AVP_AUTH_REQUEST_TYPE, 0x40, &2_u32.to_be_bytes()),
        avp(base::AVP_USER_NAME, 0x40, USER.as_bytes()),
        avp(
            base::AVP_AUTHORIZATION_LIFETIME,
            0x40,
            &AUTHORIZATION_LIFETIME.to_be_bytes(),
        ),
        avp(
            base::AVP_AUTH_GRACE_PERIOD,
            0x40,
            &AUTH_GRACE_PERIOD.to_be_bytes(),
        ),
        proxy_info(),
    ];
    let aar_wire = AuthorizationFixture::Aar.wire(aar_avps);
    let aar = parsed_authorization_request(&aar_wire);
    assert_eq!(
        aar.request().authorization_lifetime,
        Some(AUTHORIZATION_LIFETIME)
    );
    assert_eq!(aar.request().auth_grace_period, Some(AUTH_GRACE_PERIOD));
    let rebuilt = swm::build_swm_authorization_request(&aar, EncodeContext::default())
        .expect("typed AAR authorization timers must rebuild");
    assert_eq!(encode(&rebuilt), aar_wire);

    let mut aaa_avps = aaa_avps();
    let result_index = aaa_avps
        .iter()
        .position(|raw| avp_code(raw) == base::AVP_RESULT_CODE.get())
        .expect("AAA fixture contains Result-Code");
    aaa_avps.splice(
        result_index + 1..result_index + 1,
        [
            avp(base::AVP_RE_AUTH_REQUEST_TYPE, 0x40, &0_u32.to_be_bytes()),
            avp(
                base::AVP_AUTHORIZATION_LIFETIME,
                0x40,
                &AUTHORIZATION_LIFETIME.to_be_bytes(),
            ),
            avp(
                base::AVP_AUTH_GRACE_PERIOD,
                0x40,
                &AUTH_GRACE_PERIOD.to_be_bytes(),
            ),
            avp(
                base::AVP_SESSION_TIMEOUT,
                0x40,
                &SESSION_TIMEOUT.to_be_bytes(),
            ),
        ],
    );
    let aaa_wire = AuthorizationFixture::Aaa.wire(aaa_avps);
    let aaa = swm::parse_swm_authorization_answer(&decode(&aaa_wire), DecodeContext::default())
        .expect("hand-authored AAA authorization timers must parse");
    assert_eq!(aaa.authorization_lifetime, Some(AUTHORIZATION_LIFETIME));
    assert_eq!(aaa.auth_grace_period, Some(AUTH_GRACE_PERIOD));
    assert_eq!(aaa.session_timeout, Some(SESSION_TIMEOUT));
    let rebuilt = swm::build_swm_authorization_answer(&aar, &aaa, EncodeContext::default())
        .expect("typed AAA authorization timers must rebuild");
    assert_eq!(encode(&rebuilt), aaa_wire);

    let debug = format!("{aaa:?}");
    for value in [AUTHORIZATION_LIFETIME, AUTH_GRACE_PERIOD, SESSION_TIMEOUT] {
        assert!(
            !debug.contains(&value.to_string()),
            "timer values must not appear in diagnostic output"
        );
    }
}

#[test]
fn authorization_timer_zero_absent_and_bounds_semantics_are_explicit() {
    let rar = parsed_re_auth_request(&rar_wire(0xc0));
    let mut raa = SwmReAuthAnswer::for_request(
        &rar,
        SwmReAuthResult::Success,
        Redacted::from("epdg.private.invalid".to_owned()),
        Redacted::from("access.private.invalid".to_owned()),
    );
    assert_eq!(raa.authorization_lifetime, None);
    assert_eq!(raa.auth_grace_period, None);
    raa.authorization_lifetime = Some(0);
    let wire = encode(
        &swm::build_swm_re_auth_answer(&rar, &raa, EncodeContext::default())
            .expect("zero Authorization-Lifetime does not require re-auth type"),
    );
    let parsed = swm::parse_swm_re_auth_answer(&decode(&wire), DecodeContext::default())
        .expect("zero Authorization-Lifetime must parse");
    assert_eq!(parsed.authorization_lifetime, Some(0));
    assert_eq!(parsed.re_auth_request_type, None);

    raa.authorization_lifetime = Some(u32::MAX);
    raa.re_auth_request_type = Some(SwmReAuthRequestType::AuthorizeOnly);
    let wire = encode(
        &swm::build_swm_re_auth_answer(&rar, &raa, EncodeContext::default())
            .expect("maximum Unsigned32 Authorization-Lifetime must remain representable"),
    );
    let parsed = swm::parse_swm_re_auth_answer(&decode(&wire), DecodeContext::default())
        .expect("maximum Unsigned32 Authorization-Lifetime must parse");
    assert_eq!(parsed.authorization_lifetime, Some(u32::MAX));

    let aar = parsed_authorization_request(&aar_wire(0xc0));
    let mut aaa = swm::SwmAuthorizationAnswer::for_request(
        &aar,
        SwmDiameterResult::Base(base::RESULT_CODE_DIAMETER_SUCCESS),
        Redacted::from("dra.private.invalid".to_owned()),
        Redacted::from("aaa.private.invalid".to_owned()),
    );
    assert_eq!(aaa.session_timeout, None);
    aaa.session_timeout = Some(0);
    let wire = encode(
        &swm::build_swm_authorization_answer(&aar, &aaa, EncodeContext::default())
            .expect("zero Session-Timeout represents an unlimited session"),
    );
    let parsed = swm::parse_swm_authorization_answer(&decode(&wire), DecodeContext::default())
        .expect("zero Session-Timeout must parse");
    assert_eq!(parsed.session_timeout, Some(0));

    let mut aaa_avps = aaa_avps();
    let result_index = aaa_avps
        .iter()
        .position(|raw| avp_code(raw) == base::AVP_RESULT_CODE.get())
        .expect("AAA fixture contains Result-Code");
    aaa_avps.splice(
        result_index + 1..result_index + 1,
        [
            avp(base::AVP_RE_AUTH_REQUEST_TYPE, 0x40, &0_u32.to_be_bytes()),
            avp(
                base::AVP_AUTHORIZATION_LIFETIME,
                0x40,
                &u32::MAX.to_be_bytes(),
            ),
            avp(base::AVP_SESSION_TIMEOUT, 0x40, &0_u32.to_be_bytes()),
        ],
    );
    let wire = AuthorizationFixture::Aaa.wire(aaa_avps);
    let parsed = swm::parse_swm_authorization_answer(&decode(&wire), DecodeContext::default())
        .expect("unlimited Session-Timeout must not shorten an authorization lifetime");
    assert_eq!(parsed.authorization_lifetime, Some(u32::MAX));
    assert_eq!(parsed.session_timeout, Some(0));
    let rebuilt = swm::build_swm_authorization_answer(&aar, &parsed, EncodeContext::default())
        .expect("unlimited Session-Timeout must remain encodable with a lifetime");
    assert_eq!(encode(&rebuilt), wire);
}

#[test]
fn authorization_timer_semantic_violations_fail_closed() {
    for fixture in [AuthorizationFixture::Raa, AuthorizationFixture::Aaa] {
        let mut avps = fixture.avps();
        avps.push(avp(
            base::AVP_AUTHORIZATION_LIFETIME,
            0x40,
            &1_u32.to_be_bytes(),
        ));
        let error = assert_bounded_rejection(
            fixture,
            "positive Authorization-Lifetime without Re-Auth-Request-Type",
            &fixture.wire(avps),
            DecodeContext::default(),
        );
        assert!(matches!(error.code(), DecodeErrorCode::Structural { .. }));
    }

    let mut aaa_avps = aaa_avps();
    aaa_avps.extend([
        avp(base::AVP_RE_AUTH_REQUEST_TYPE, 0x40, &0_u32.to_be_bytes()),
        avp(
            base::AVP_AUTHORIZATION_LIFETIME,
            0x40,
            &301_u32.to_be_bytes(),
        ),
        avp(base::AVP_SESSION_TIMEOUT, 0x40, &300_u32.to_be_bytes()),
    ]);
    let error = assert_bounded_rejection(
        AuthorizationFixture::Aaa,
        "Session-Timeout smaller than Authorization-Lifetime",
        &AuthorizationFixture::Aaa.wire(aaa_avps),
        DecodeContext::default(),
    );
    assert!(matches!(error.code(), DecodeErrorCode::Structural { .. }));

    let rar = parsed_re_auth_request(&rar_wire(0xc0));
    let mut raa = SwmReAuthAnswer::for_request(
        &rar,
        SwmReAuthResult::Success,
        Redacted::from("epdg.private.invalid".to_owned()),
        Redacted::from("access.private.invalid".to_owned()),
    );
    raa.authorization_lifetime = Some(1);
    let error = swm::build_swm_re_auth_answer(&rar, &raa, EncodeContext::default())
        .expect_err("builder must reject a positive lifetime without re-auth type");
    assert!(!error.to_string().contains('1'));

    let aar = parsed_authorization_request(&aar_wire(0xc0));
    let mut aaa = swm::SwmAuthorizationAnswer::for_request(
        &aar,
        SwmDiameterResult::Base(base::RESULT_CODE_DIAMETER_SUCCESS),
        Redacted::from("dra.private.invalid".to_owned()),
        Redacted::from("aaa.private.invalid".to_owned()),
    );
    aaa.re_auth_request_type = Some(SwmReAuthRequestType::AuthorizeOnly);
    aaa.authorization_lifetime = Some(301);
    aaa.session_timeout = Some(300);
    let error = swm::build_swm_authorization_answer(&aar, &aaa, EncodeContext::default())
        .expect_err("builder must reject an undersized Session-Timeout");
    assert!(!error.to_string().contains("300"));
    assert!(!error.to_string().contains("301"));
}

#[test]
fn aar_lifetime_hint_bounds_successful_aaa_build_and_correlation() {
    const HINT: u32 = 600;
    const LIFETIME_ERROR: &str =
        "success-class SWm AAA must honor the AAR Authorization-Lifetime ceiling";

    let mut request_avps = aar_avps();
    let proxy_index = request_avps
        .iter()
        .position(|raw| avp_code(raw) == base::AVP_PROXY_INFO.get())
        .expect("AAR fixture contains Proxy-Info");
    request_avps.insert(
        proxy_index,
        avp(base::AVP_AUTHORIZATION_LIFETIME, 0x40, &HINT.to_be_bytes()),
    );
    let request = parsed_authorization_request(&AuthorizationFixture::Aar.wire(request_avps));

    let success_results = [
        SwmDiameterResult::Base(base::RESULT_CODE_DIAMETER_SUCCESS),
        SwmDiameterResult::Base(2_002),
        SwmDiameterResult::Experimental {
            vendor_id: VENDOR_ID_3GPP,
            code: 2_002,
        },
    ];
    for result in success_results {
        let mut answer = swm::SwmAuthorizationAnswer::for_request(
            &request,
            result,
            Redacted::from("dra.private.invalid".to_owned()),
            Redacted::from("aaa.private.invalid".to_owned()),
        );
        let error =
            swm::build_swm_authorization_answer(&request, &answer, EncodeContext::default())
                .expect_err("every success-class AAA must return a lifetime after an AAR hint");
        assert_eq!(
            error.code(),
            &EncodeErrorCode::Structural {
                reason: LIFETIME_ERROR,
            }
        );
        assert!(!error.to_string().contains(&HINT.to_string()));

        answer.re_auth_request_type = Some(SwmReAuthRequestType::AuthorizeOnly);
        answer.authorization_lifetime = Some(HINT + 1);
        let error =
            swm::build_swm_authorization_answer(&request, &answer, EncodeContext::default())
                .expect_err("success-class AAA must not exceed the AAR lifetime ceiling");
        assert_eq!(
            error.code(),
            &EncodeErrorCode::Structural {
                reason: LIFETIME_ERROR,
            }
        );
        assert!(!error.to_string().contains(&(HINT + 1).to_string()));

        for accepted in [HINT, HINT - 1] {
            answer.authorization_lifetime = Some(accepted);
            let built =
                swm::build_swm_authorization_answer(&request, &answer, EncodeContext::default())
                    .expect("success-class AAA may equal or tighten the AAR lifetime ceiling");
            let received = parsed_authorization_answer(&decode(&encode(&built)), CONNECTION_A);
            request
                .clone()
                .correlate_answer(received)
                .expect("equal or shorter success-class AAA lifetime must correlate");
        }
    }

    let result_avp = |result: SwmDiameterResult| match result {
        SwmDiameterResult::Base(code) => avp(base::AVP_RESULT_CODE, 0x40, &code.to_be_bytes()),
        SwmDiameterResult::Experimental { vendor_id, code } => {
            let children: Vec<u8> = [
                avp(base::AVP_VENDOR_ID, 0x40, &vendor_id.get().to_be_bytes()),
                avp(
                    base::AVP_EXPERIMENTAL_RESULT_CODE,
                    0x40,
                    &code.to_be_bytes(),
                ),
            ]
            .into_iter()
            .flatten()
            .collect();
            avp(base::AVP_EXPERIMENTAL_RESULT, 0x40, &children)
        }
    };
    for result in success_results {
        for received_lifetime in [None, Some(HINT + 1)] {
            let mut answer_avps = aaa_avps();
            answer_avps.retain(|raw| avp_code(raw) != swm::AVP_APN_CONFIGURATION.get());
            let result_index = answer_avps
                .iter()
                .position(|raw| avp_code(raw) == base::AVP_RESULT_CODE.get())
                .expect("AAA fixture contains Result-Code");
            answer_avps[result_index] = result_avp(result);
            if let Some(lifetime) = received_lifetime {
                answer_avps.splice(
                    result_index + 1..result_index + 1,
                    [
                        avp(base::AVP_RE_AUTH_REQUEST_TYPE, 0x40, &0_u32.to_be_bytes()),
                        avp(
                            base::AVP_AUTHORIZATION_LIFETIME,
                            0x40,
                            &lifetime.to_be_bytes(),
                        ),
                    ],
                );
            }
            let wire = AuthorizationFixture::Aaa.wire(answer_avps);
            let received = parsed_authorization_answer(&decode(&wire), CONNECTION_A);
            let error = request
                .clone()
                .correlate_answer(received)
                .expect_err("received success-class AAA must honor the lifetime ceiling");
            assert_eq!(
                error,
                swm::SwmAuthorizationCorrelationError::AuthorizationLifetimeMismatch
            );
            assert_eq!(error.as_str(), "swm_authorization_lifetime_mismatch");
            assert_eq!(error.to_string(), "swm_authorization_lifetime_mismatch");
        }
    }

    let failed_answer = swm::SwmAuthorizationAnswer::for_request(
        &request,
        SwmDiameterResult::Experimental {
            vendor_id: VENDOR_ID_3GPP,
            code: 5_001,
        },
        Redacted::from("dra.private.invalid".to_owned()),
        Redacted::from("aaa.private.invalid".to_owned()),
    );
    let built =
        swm::build_swm_authorization_answer(&request, &failed_answer, EncodeContext::default())
            .expect("an unsuccessful AAA need not grant an authorization lifetime");
    let received = parsed_authorization_answer(&decode(&encode(&built)), CONNECTION_A);
    request
        .correlate_answer(received)
        .expect("the request lifetime ceiling applies only to successful AAA");
}

#[test]
fn authorization_timer_cardinality_roles_and_types_fail_closed() {
    for (fixture, code) in [
        (AuthorizationFixture::Raa, base::AVP_AUTHORIZATION_LIFETIME),
        (AuthorizationFixture::Raa, base::AVP_AUTH_GRACE_PERIOD),
        (AuthorizationFixture::Aar, base::AVP_AUTHORIZATION_LIFETIME),
        (AuthorizationFixture::Aar, base::AVP_AUTH_GRACE_PERIOD),
        (AuthorizationFixture::Aaa, base::AVP_AUTHORIZATION_LIFETIME),
        (AuthorizationFixture::Aaa, base::AVP_AUTH_GRACE_PERIOD),
        (AuthorizationFixture::Aaa, base::AVP_SESSION_TIMEOUT),
    ] {
        let mut avps = fixture.avps();
        avps.extend([
            avp(code, 0x40, &0_u32.to_be_bytes()),
            avp(code, 0x40, &0_u32.to_be_bytes()),
        ]);
        let error = assert_bounded_rejection(
            fixture,
            "a duplicate authorization timer",
            &fixture.wire(avps),
            DecodeContext::default(),
        );
        assert_eq!(error.code(), &DecodeErrorCode::DuplicateIe);
    }

    for (fixture, code) in [
        (AuthorizationFixture::Rar, base::AVP_AUTHORIZATION_LIFETIME),
        (AuthorizationFixture::Rar, base::AVP_AUTH_GRACE_PERIOD),
        (AuthorizationFixture::Rar, base::AVP_SESSION_TIMEOUT),
        (AuthorizationFixture::Raa, base::AVP_SESSION_TIMEOUT),
        (AuthorizationFixture::Aar, base::AVP_SESSION_TIMEOUT),
    ] {
        let mut avps = fixture.avps();
        avps.push(avp(code, 0x40, &0_u32.to_be_bytes()));
        let error = assert_bounded_rejection(
            fixture,
            "an authorization timer in the wrong command role",
            &fixture.wire(avps),
            DecodeContext::default(),
        );
        assert!(matches!(error.code(), DecodeErrorCode::Structural { .. }));
    }

    for (fixture, code) in [
        (AuthorizationFixture::Raa, base::AVP_AUTHORIZATION_LIFETIME),
        (AuthorizationFixture::Raa, base::AVP_AUTH_GRACE_PERIOD),
        (AuthorizationFixture::Aar, base::AVP_AUTHORIZATION_LIFETIME),
        (AuthorizationFixture::Aar, base::AVP_AUTH_GRACE_PERIOD),
        (AuthorizationFixture::Aaa, base::AVP_SESSION_TIMEOUT),
    ] {
        let mut avps = fixture.avps();
        avps.push(avp(code, 0x40, &[0, 0, 1]));
        let error = assert_bounded_rejection(
            fixture,
            "a non-Unsigned32 authorization timer",
            &fixture.wire(avps),
            DecodeContext::default(),
        );
        assert!(matches!(
            error.code(),
            DecodeErrorCode::InvalidLength { .. }
        ));
    }
}

#[test]
fn role_forbidden_additional_avps_fail_on_decode_and_encode() {
    for fixture in AUTHORIZATION_FIXTURES {
        for (code, value) in [
            (base::AVP_TERMINATION_CAUSE, 1_u32.to_be_bytes()),
            (base::AVP_AUTH_SESSION_STATE, 0_u32.to_be_bytes()),
        ] {
            let mut avps = fixture.avps();
            avps.push(avp(code, 0x40, &value));
            let wire = fixture.wire(avps);
            assert_bounded_rejection(
                fixture,
                "a command-forbidden lifecycle AVP",
                &wire,
                DecodeContext::default(),
            );
        }
    }

    let mut aar_with_class = aar_avps();
    aar_with_class.push(avp(base::AVP_CLASS, 0x40, b"invalid-aar-class"));
    assert_bounded_rejection(
        AuthorizationFixture::Aar,
        "RFC 4005 AAR Class occurrence zero",
        &AuthorizationFixture::Aar.wire(aar_with_class),
        DecodeContext::default(),
    );

    for fixture in [AuthorizationFixture::Rar, AuthorizationFixture::Aar] {
        for code in [
            base::AVP_ERROR_MESSAGE,
            base::AVP_ERROR_REPORTING_HOST,
            base::AVP_FAILED_AVP,
        ] {
            let mut avps = fixture.avps();
            let value = if code == base::AVP_FAILED_AVP {
                avp(base::AVP_ORIGIN_HOST, 0x40, b"failed.private.invalid")
            } else {
                b"answer-only.private.invalid".to_vec()
            };
            avps.push(avp(code, 0x40, &value));
            assert_bounded_rejection(
                fixture,
                "an answer-only AVP in a request",
                &fixture.wire(avps),
                DecodeContext::default(),
            );
        }
        for (code, value) in [
            (
                base::AVP_REDIRECT_HOST,
                b"aaa://redirect.example.invalid".to_vec(),
            ),
            (base::AVP_REDIRECT_HOST_USAGE, 0_u32.to_be_bytes().to_vec()),
            (
                base::AVP_REDIRECT_MAX_CACHE_TIME,
                60_u32.to_be_bytes().to_vec(),
            ),
        ] {
            let mut avps = fixture.avps();
            avps.push(avp(code, 0x40, &value));
            assert_bounded_rejection(
                fixture,
                "an answer-only redirect AVP in a request",
                &fixture.wire(avps),
                DecodeContext::default(),
            );
        }
    }

    let request = parsed_authorization_request(&aar_wire(0xc0));
    let mut answer =
        swm::parse_swm_authorization_answer(&decode(&aaa_wire()), DecodeContext::default())
            .expect("AAA fixture must parse");
    answer.additional_avps.push(
        SwmAdditionalAvp::new(
            AvpHeader::ietf(base::AVP_TERMINATION_CAUSE, true),
            1_u32.to_be_bytes().to_vec(),
            EncodeContext::default(),
        )
        .expect("Termination-Cause test AVP must frame"),
    );
    swm::build_swm_authorization_answer(&request, &answer, EncodeContext::default())
        .expect_err("AAA encode must reject command-forbidden Termination-Cause");
}

#[test]
fn every_authorization_command_rejects_malformed_grouped_and_unknown_mandatory_avps() {
    for fixture in AUTHORIZATION_FIXTURES {
        let mut malformed_grouped = fixture.avps();
        let grouped_offset = DIAMETER_HEADER_LEN
            + malformed_grouped
                .iter()
                .take_while(|raw| avp_code(raw) != base::AVP_PROXY_INFO.get())
                .map(Vec::len)
                .sum::<usize>();
        replace_first_avp(
            &mut malformed_grouped,
            base::AVP_PROXY_INFO,
            avp(base::AVP_PROXY_INFO, 0x40, &[0, 0, 0]),
        );
        let wire = fixture.wire(malformed_grouped);
        let error = assert_bounded_rejection(
            fixture,
            "a malformed grouped AVP",
            &wire,
            DecodeContext::default(),
        );
        assert!(error.offset() >= grouped_offset);

        let mut unknown_mandatory = fixture.avps();
        let unknown_offset =
            DIAMETER_HEADER_LEN + unknown_mandatory.iter().map(Vec::len).sum::<usize>();
        unknown_mandatory.push(avp(
            AvpCode::new(UNKNOWN + 99),
            0x40,
            b"unknown-mandatory-private-value",
        ));
        let wire = fixture.wire(unknown_mandatory);
        let error = assert_bounded_rejection(
            fixture,
            "an unknown mandatory AVP",
            &wire,
            DecodeContext::default(),
        );
        assert_eq!(error.code(), &DecodeErrorCode::UnknownCriticalIe);
        assert_eq!(error.offset(), unknown_offset);
    }
}

#[test]
fn every_authorization_command_enforces_message_and_typed_collection_bounds() {
    for fixture in AUTHORIZATION_FIXTURES {
        let wire = fixture.wire(fixture.avps());
        let decode_error = Message::decode(
            &wire,
            DecodeContext {
                max_message_len: wire.len().saturating_sub(1),
                ..DecodeContext::default()
            },
        )
        .expect_err("message framing must enforce the configured byte bound");
        assert_eq!(decode_error.code(), &DecodeErrorCode::MessageLengthExceeded);
        assert!(decode_error.offset() <= wire.len());

        let mut oversized = fixture.avps();
        oversized.retain(|raw| {
            let code = avp_code(raw);
            code != UNKNOWN && code != UNKNOWN + 1
        });
        for code in 200_000..200_129 {
            oversized.push(avp(AvpCode::new(code), 0x00, b"bounded-private-extension"));
        }
        let wire = fixture.wire(oversized);
        let error = assert_bounded_rejection(
            fixture,
            "an oversized typed extension collection",
            &wire,
            DecodeContext {
                max_ies: 512,
                ..DecodeContext::default()
            },
        );
        assert_eq!(error.code(), &DecodeErrorCode::IeCountExceeded);
    }
}

#[test]
fn unknown_policy_and_duplicate_singletons_fail_closed() {
    let wire = rar_wire(0xc0);
    let preserved = swm::parse_swm_re_auth_request(
        &decode(&wire),
        DecodeContext {
            unknown_ie_policy: UnknownIePolicy::Preserve,
            ..DecodeContext::default()
        },
    )
    .expect("optional extension must be preserved");
    assert_eq!(preserved.additional_avps.len(), 1);
    let dropped = swm::parse_swm_re_auth_request(
        &decode(&wire),
        DecodeContext {
            unknown_ie_policy: UnknownIePolicy::Drop,
            ..DecodeContext::default()
        },
    )
    .expect("optional extension may be dropped");
    assert!(dropped.additional_avps.is_empty());
    let rejected = swm::parse_swm_re_auth_request(
        &decode(&wire),
        DecodeContext {
            unknown_ie_policy: UnknownIePolicy::Reject,
            ..DecodeContext::default()
        },
    )
    .expect_err("reject policy must reject unknown extension");
    assert_eq!(rejected.code(), &DecodeErrorCode::UnknownCriticalIe);

    let mut avps = rar_avps();
    avps.push(avp(base::AVP_SESSION_ID, 0x40, SESSION.as_bytes()));
    let duplicate = message(258, 0xc0, HOP_RAR, END_RAR, avps);
    let error = swm::parse_swm_re_auth_request(&decode(&duplicate), DecodeContext::default())
        .expect_err("duplicate Session-Id must fail");
    assert_eq!(error.code(), &DecodeErrorCode::DuplicateIe);
}

#[test]
fn vendor_specific_extension_code_collisions_round_trip_by_exact_key() {
    let original = typed_rar_envelope();
    let transaction = original.transaction();
    let mut request = original.request().clone();
    request.additional_avps.push(
        SwmAdditionalAvp::new(
            AvpHeader::vendor(base::AVP_SESSION_ID, VENDOR_ID_3GPP, false),
            b"private-vendor-extension".to_vec(),
            EncodeContext::default(),
        )
        .expect("M-clear vendor extension must frame"),
    );
    let envelope = SwmReAuthRequestEnvelope::for_outbound(
        request,
        transaction,
        expected_re_auth_peer(CONNECTION_A),
    );
    let built = swm::build_swm_re_auth_request(&envelope, EncodeContext::default())
        .expect("vendor-specific numeric collision must encode");
    let wire = encode(&built);
    let parsed = swm::parse_swm_re_auth_request(
        &decode(&wire),
        DecodeContext {
            unknown_ie_policy: UnknownIePolicy::Preserve,
            ..DecodeContext::default()
        },
    )
    .expect("vendor-specific numeric collision must not shadow the IETF key");
    assert!(parsed.additional_avps.iter().any(|avp| {
        avp.code() == base::AVP_SESSION_ID && avp.vendor_id() == Some(VENDOR_ID_3GPP)
    }));
}

#[test]
fn authorization_diameter_identities_require_ascii_on_decode_and_encode() {
    let mut avps = rar_avps();
    let index = avps
        .iter()
        .position(|raw| {
            u32::from_be_bytes(raw[0..4].try_into().expect("fixed AVP code"))
                == base::AVP_ORIGIN_HOST.get()
        })
        .expect("RAR Origin-Host fixture");
    avps[index] = avp(base::AVP_ORIGIN_HOST, 0x40, "épdg.invalid".as_bytes());
    let wire = message(258, 0xc0, HOP_RAR, END_RAR, avps);
    assert!(
        swm::parse_swm_re_auth_request(&decode(&wire), DecodeContext::default()).is_err(),
        "received DiameterIdentity must contain ASCII"
    );

    let original = typed_rar_envelope();
    let mut request = original.request().clone();
    request.destination_host = Redacted::from("épdg.invalid".to_owned());
    let invalid = SwmReAuthRequestEnvelope::for_outbound(
        request,
        original.transaction(),
        expected_re_auth_peer(CONNECTION_A),
    );
    assert!(
        swm::build_swm_re_auth_request(&invalid, EncodeContext::default()).is_err(),
        "originated DiameterIdentity must contain ASCII"
    );
}

fn typed_rar_envelope() -> SwmReAuthRequestEnvelope {
    SwmReAuthRequestEnvelope::for_outbound(
        SwmReAuthRequest {
            session_id: Redacted::from(SESSION.to_owned()),
            origin_host: Redacted::from("aaa.private.invalid".to_owned()),
            origin_realm: Redacted::from("private.invalid".to_owned()),
            destination_realm: Redacted::from("access.private.invalid".to_owned()),
            destination_host: Redacted::from("epdg.private.invalid".to_owned()),
            re_auth_request_type: SwmReAuthRequestType::AuthorizeOnly,
            user_name: Redacted::from(USER.to_owned()),
            drmp: None,
            route_records: Vec::new(),
            additional_avps: Vec::new(),
        },
        SwmDiameterTransaction::new(HOP_RAR, END_RAR),
        expected_re_auth_peer(CONNECTION_A),
    )
}

#[test]
fn update_sequence_caches_answer_and_rfc_compliant_aar_retry() {
    let rar = typed_rar_envelope();
    let raa = SwmReAuthAnswer::for_request(
        &rar,
        SwmReAuthResult::Success,
        Redacted::from("epdg.private.invalid".to_owned()),
        Redacted::from("access.private.invalid".to_owned()),
    );
    let accepted = SwmAcceptedAuthorizationUpdate::accept(rar, raa, EncodeContext::default())
        .expect("successful RAA must commit");
    assert_eq!(
        encode(&accepted.replay_re_auth_answer()),
        encode(&accepted.replay_re_auth_answer())
    );
    let mut pending = accepted
        .begin_authorization(
            SwmAuthorizationRequest {
                session_id: Redacted::from(SESSION.to_owned()),
                origin_host: Redacted::from("epdg.private.invalid".to_owned()),
                origin_realm: Redacted::from("private.invalid".to_owned()),
                destination_realm: Redacted::from("aaa.private.invalid".to_owned()),
                destination_host: None,
                user_name: Redacted::from(USER.to_owned()),
                auth_request_type: AuthRequestType::AuthorizeOnly,
                authorization_lifetime: None,
                auth_grace_period: None,
                aar_flags: None,
                ue_local_ip_address: None,
                high_priority_access_info: None,
                drmp: None,
                route_records: Vec::new(),
                additional_avps: Vec::new(),
            },
            SwmDiameterTransaction::new(HOP_AAR, END_AAR),
            expected_authorization_peer(CONNECTION_A),
            EncodeContext::default(),
        )
        .expect("matching AAR must commit");
    let initial = encode(&pending.initial_authorization_request());
    let retry = encode(&pending.retransmit_authorization_request());
    assert_eq!(initial[4] & 0x10, 0);
    assert_eq!(retry[4] & 0x10, 0);
    assert_eq!(initial, retry);
    assert_eq!(
        retry,
        encode(&pending.retransmit_authorization_request()),
        "ordinary cached retries must remain byte-identical"
    );
    pending
        .mark_for_failover_retransmission(
            HOP_FAILOVER,
            expected_authorization_peer(CONNECTION_B),
            EncodeContext::default(),
        )
        .expect("queued AAR may transition after link failover");
    let failover_retry = encode(&pending.retransmit_authorization_request());
    assert_eq!(failover_retry[4] & 0x10, 0x10);
    assert_eq!(&failover_retry[5..12], &initial[5..12]);
    assert_eq!(&failover_retry[12..16], &HOP_FAILOVER.to_be_bytes());
    assert_eq!(&failover_retry[16..], &initial[16..]);
    let aaa = message(
        265,
        0x40,
        HOP_FAILOVER,
        END_AAR,
        vec![
            avp(base::AVP_SESSION_ID, 0x40, SESSION.as_bytes()),
            avp(
                base::AVP_AUTH_APPLICATION_ID,
                0x40,
                &swm::APPLICATION_ID.get().to_be_bytes(),
            ),
            avp(swm::AVP_AUTH_REQUEST_TYPE, 0x40, &2_u32.to_be_bytes()),
            avp(
                base::AVP_RESULT_CODE,
                0x40,
                &base::RESULT_CODE_DIAMETER_SUCCESS.to_be_bytes(),
            ),
            avp(base::AVP_ORIGIN_HOST, 0x40, b"aaa.private.invalid"),
            avp(base::AVP_ORIGIN_REALM, 0x40, b"aaa.private.invalid"),
            avp(base::AVP_USER_NAME, 0x40, USER.as_bytes()),
        ],
    );
    let aaa = parsed_authorization_answer(&decode(&aaa), CONNECTION_B);
    let completed = pending.complete(aaa).expect("terminal AAA must correlate");
    assert_eq!(
        completed.authorization().answer().result,
        SwmDiameterResult::Base(base::RESULT_CODE_DIAMETER_SUCCESS)
    );
}

#[test]
fn update_sequence_rejects_non_successful_raa_and_identity_drift() {
    let rar = typed_rar_envelope();
    let rejected = SwmReAuthAnswer::for_request(
        &rar,
        SwmReAuthResult::UnableToComply,
        Redacted::from("epdg.private.invalid".to_owned()),
        Redacted::from("access.private.invalid".to_owned()),
    );
    assert!(
        SwmAcceptedAuthorizationUpdate::accept(rar, rejected, EncodeContext::default(),).is_err()
    );

    let rar = typed_rar_envelope();
    let accepted_answer = SwmReAuthAnswer::for_request(
        &rar,
        SwmReAuthResult::Success,
        Redacted::from("epdg.private.invalid".to_owned()),
        Redacted::from("access.private.invalid".to_owned()),
    );
    let accepted =
        SwmAcceptedAuthorizationUpdate::accept(rar, accepted_answer, EncodeContext::default())
            .expect("successful RAA must commit");
    let drifted = SwmAuthorizationRequest {
        session_id: Redacted::from("different-session".to_owned()),
        origin_host: Redacted::from("epdg.private.invalid".to_owned()),
        origin_realm: Redacted::from("private.invalid".to_owned()),
        destination_realm: Redacted::from("aaa.private.invalid".to_owned()),
        destination_host: None,
        user_name: Redacted::from(USER.to_owned()),
        auth_request_type: AuthRequestType::AuthorizeOnly,
        authorization_lifetime: None,
        auth_grace_period: None,
        aar_flags: None,
        ue_local_ip_address: None,
        high_priority_access_info: None,
        drmp: None,
        route_records: Vec::new(),
        additional_avps: Vec::new(),
    };
    assert!(accepted
        .begin_authorization(
            drifted,
            SwmDiameterTransaction::new(HOP_AAR, END_AAR),
            expected_authorization_peer(CONNECTION_A),
            EncodeContext::default(),
        )
        .is_err());
}

#[test]
fn debug_output_redacts_session_user_and_ip() {
    let request =
        swm::parse_swm_authorization_request(&decode(&aar_wire(0xc0)), DecodeContext::default())
            .expect("AAR must parse");
    let debug = format!("{request:?}");
    assert!(!debug.contains(SESSION));
    assert!(!debug.contains(USER));
    assert!(!debug.contains("198.51.100.10"));

    let envelope = parsed_authorization_request(&aar_wire(0xc0));
    let envelope_debug = format!("{envelope:?}");
    assert!(!envelope_debug.contains(SESSION));
    assert!(!envelope_debug.contains(USER));
    assert!(!envelope_debug.contains("dra.private.invalid"));
}
