//! Kernel-independent re-pin coordination primitives.

use std::fmt;
use std::num::{NonZeroU128, NonZeroU64};

use sha2::{Digest, Sha256};

use crate::error::IpsecLbError;
use crate::failover::{AntiReplayResume, SendIvCounterMode, SendIvForwardJump};
use crate::model::{ClusterNode, IpAddress, SaId, SteerKey, SteeringRule};
use crate::ports::{OwnershipFencer, OwnershipSource, RePinAuditSink, SteeringBackend};

/// Monotonic ownership fence token.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Ord, PartialOrd)]
pub struct OwnershipFence(NonZeroU64);

impl OwnershipFence {
    /// Build a non-zero ownership fence token.
    pub fn new(value: u64) -> Result<Self, IpsecLbError> {
        let Some(value) = NonZeroU64::new(value) else {
            return Err(IpsecLbError::invalid_config(
                "fence",
                "fence token must be non-zero",
            ));
        };
        Ok(Self(value))
    }

    /// Return the numeric fence value.
    #[must_use]
    pub const fn get(self) -> u64 {
        self.0.get()
    }
}

/// Authoritative SA ownership metadata used to prepare a fenced transition.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OwnershipSnapshot {
    owner: ClusterNode,
    fence: OwnershipFence,
}

impl OwnershipSnapshot {
    /// Build an owner/fence snapshot.
    #[must_use]
    pub const fn new(owner: ClusterNode, fence: OwnershipFence) -> Self {
        Self { owner, fence }
    }

    /// Return the authoritative owner.
    #[must_use]
    pub fn owner(&self) -> &ClusterNode {
        &self.owner
    }

    /// Return the authoritative predecessor fence.
    #[must_use]
    pub const fn fence(&self) -> OwnershipFence {
        self.fence
    }
}

/// Stable identity for one ownership transition and all of its retries.
///
/// Callers generate one non-zero, deployment-unique value before starting a
/// re-pin and retain it when replaying the same request. A fresh transition,
/// including a later ABA return to the same owner, MUST use a new value.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Ord, PartialOrd)]
pub struct OwnershipTransitionId(NonZeroU128);

impl OwnershipTransitionId {
    /// Build a non-zero transition identity.
    pub fn new(value: u128) -> Result<Self, IpsecLbError> {
        let Some(value) = NonZeroU128::new(value) else {
            return Err(IpsecLbError::invalid_config(
                "transition_id",
                "ownership transition ID must be non-zero",
            ));
        };
        Ok(Self(value))
    }

    /// Return the numeric transition identity.
    #[must_use]
    pub const fn get(self) -> u128 {
        self.0.get()
    }
}

/// Collision-resistant binding of an ownership transition to its full re-pin
/// request.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Ord, PartialOrd)]
pub struct OwnershipTransitionFingerprint([u8; 32]);

impl OwnershipTransitionFingerprint {
    /// Build an opaque fingerprint for direct ownership-fencer integrations.
    ///
    /// Re-pin callers should use [`RePinRequest::ownership_fingerprint`], which
    /// canonically binds every steering and resume-evidence field.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Return the fingerprint bytes.
    #[must_use]
    pub const fn as_bytes(self) -> [u8; 32] {
        self.0
    }
}

/// Source of the resumed SA key material.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ResumeKeySource {
    /// A live standby already held the SA keys before owner loss.
    ///
    /// For a counter-based mode, live mirroring does not make the mirrored send
    /// counter current at the instant of failure, so the resume requires a
    /// forward-jump. Random-IV IKE requires the explicit CSPRNG attestation
    /// instead.
    LiveMirrored,
    /// No standby has keys; the caller must rekey or force UE re-attach.
    RekeyOrReattachFallback,
    /// Persisted key material was read on the re-pin path.
    ///
    /// Counter-based same-SPI use requires a validated outbound IV
    /// forward-jump. Random-IV IKE requires the explicit CSPRNG attestation.
    PersistedKeyMaterial,
}

/// Attestation for an IKE encrypt-then-MAC SA whose outbound IVs are random.
///
/// This evidence is appropriate only when every newly encrypted IKE message
/// obtains an independent, unpredictable IV from a cryptographically secure
/// random source. It is not an IV value, counter, key, or proof generated by
/// the SDK. The IKE protected-payload owner remains responsible for satisfying
/// the attested invariant for the lifetime of the resumed SA.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IkeRandomIvAttestation {
    /// Every outbound protected message obtains a fresh independent CSPRNG IV.
    FreshIndependentCsprngIvPerMessage,
}

/// Protocol-specific outbound-IV evidence for a same-SPI resume.
///
/// Counter fields exist only in [`Self::CounterBased`], so an IKE
/// encrypt-then-MAC resume cannot claim placeholder counters. [`Self::Unspecified`]
/// lets legacy or ambiguously decoded evidence reach the validation boundary,
/// where it is rejected without changing ownership or steering.
///
/// Random-IV evidence cannot be constructed without its attestation, nor can
/// it carry dummy counter fields:
///
/// ```compile_fail
/// use opc_ipsec_lb::SameSpiOutboundIvResume;
///
/// let _ = SameSpiOutboundIvResume::IkeRandomIv {
///     checkpointed_send_iv_next: 0,
///     restored_send_iv_next: 0,
/// };
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SameSpiOutboundIvResume {
    /// Legacy, missing, or ambiguously decoded outbound-IV evidence.
    Unspecified,
    /// Resume a protocol-defined monotonic outbound counter.
    CounterBased {
        /// Last checkpointed or mirrored next outbound IV/counter value.
        ///
        /// This is a stale lower bound, not proof that the old owner stopped
        /// before consuming later counter values. ESP checkpoints must be
        /// non-zero, and the ESP counter mode defines peer receive lag relative
        /// to this value minus one.
        checkpointed_send_iv_next: u64,
        /// Next outbound IV/counter value actually restored on the survivor.
        restored_send_iv_next: u64,
        /// Mandatory stale-counter forward-jump evidence.
        ///
        /// `None` is representable so decoded or legacy counter evidence can be
        /// rejected at the re-pin boundary.
        forward_jump: Option<SendIvForwardJump>,
    },
    /// Resume an IKE encrypt-then-MAC SA that uses random outbound IVs.
    ///
    /// No counter or forward-jump fields exist in this variant. It is valid
    /// only for [`SaId::Ike`].
    IkeRandomIv {
        /// Explicit caller attestation of the resumed IKE IV-generation mode.
        attestation: IkeRandomIvAttestation,
    },
}

/// Evidence required before installing an IPsec/IKE same-SPI re-pin.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SameSpiResume {
    /// SA before owner loss.
    pub previous_sa: SaId,
    /// SA resumed on the survivor.
    pub resumed_sa: SaId,
    /// Outbound-IV safety evidence for the resumed cryptographic mode.
    pub outbound_iv: SameSpiOutboundIvResume,
    /// Inbound anti-replay restore evidence (ESP sequence or IKE Message ID).
    pub anti_replay: AntiReplayResume,
    /// Key-custody path used for the resumed SA.
    pub key_source: ResumeKeySource,
}

impl SameSpiResume {
    /// Validate that this evidence can support near-hitless same-SPI re-pin.
    pub fn validate_for_repin(self, expected_sa: SaId) -> Result<(), IpsecLbError> {
        validate_sa_identifier(expected_sa)?;
        if self.previous_sa != expected_sa || self.resumed_sa != expected_sa {
            return Err(IpsecLbError::unsafe_resume(
                "same-SPI re-pin requires the resumed SA to keep the original protocol and SPI",
            ));
        }
        match self.key_source {
            ResumeKeySource::LiveMirrored | ResumeKeySource::PersistedKeyMaterial => {}
            ResumeKeySource::RekeyOrReattachFallback => {
                return Err(IpsecLbError::unsafe_resume(
                    "rekey or UE re-attach fallback cannot claim same-SPI re-pin",
                ));
            }
        }

        match self.outbound_iv {
            SameSpiOutboundIvResume::Unspecified => {
                return Err(IpsecLbError::unsafe_resume(
                    "same-SPI re-pin requires explicit outbound IV resume evidence",
                ));
            }
            SameSpiOutboundIvResume::CounterBased {
                checkpointed_send_iv_next,
                restored_send_iv_next,
                forward_jump,
            } => {
                let Some(forward_jump) = forward_jump else {
                    return Err(IpsecLbError::unsafe_resume(
                        "counter-based same-SPI re-pin requires send IV forward-jump evidence",
                    ));
                };
                forward_jump.validate_restored_next(
                    expected_sa,
                    checkpointed_send_iv_next,
                    restored_send_iv_next,
                )?;
            }
            SameSpiOutboundIvResume::IkeRandomIv { attestation } => {
                if !matches!(expected_sa, SaId::Ike { .. }) {
                    return Err(IpsecLbError::unsafe_resume(
                        "random-IV same-SPI resume is valid only for an IKE SA",
                    ));
                }
                match attestation {
                    IkeRandomIvAttestation::FreshIndependentCsprngIvPerMessage => {}
                }
            }
        }
        self.anti_replay.validate()
    }
}

/// Request to fence ownership and install a steer override for a resumed SA.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RePinRequest {
    /// SA being re-pinned.
    pub sa: SaId,
    /// Stable identity reused only for retries of this transition.
    pub transition_id: OwnershipTransitionId,
    /// Exact authoritative fence held by `previous_owner` when prepared.
    /// Obtain it with [`OwnershipSource::sa_ownership`].
    pub previous_fence: OwnershipFence,
    /// Owner expected before the transition.
    pub previous_owner: ClusterNode,
    /// New owner after failover.
    pub new_owner: ClusterNode,
    /// Steering override to install after fencing.
    pub rule: SteeringRule,
    /// Same-SPI resume evidence.
    pub resume: SameSpiResume,
}

impl RePinRequest {
    /// Hash the complete safety-critical request into a stable transition
    /// fingerprint used by ownership commit and recovery.
    ///
    /// Counter-based requests retain the original v1 byte encoding so an
    /// in-flight IKE-AEAD or ESP transition remains recoverable across a
    /// rolling SDK upgrade. New random-IV and unspecified evidence use the v2
    /// domain and mode-tagged encoding.
    #[must_use]
    pub fn ownership_fingerprint(&self) -> OwnershipTransitionFingerprint {
        let mut hasher = Sha256::new();
        match self.resume.outbound_iv {
            SameSpiOutboundIvResume::CounterBased {
                checkpointed_send_iv_next,
                restored_send_iv_next,
                forward_jump,
            } => {
                hasher.update(b"opc-ipsec-lb/repin-transition/v1");
                hash_request_prefix(&mut hasher, self);
                hash_counter_resume_v1(
                    &mut hasher,
                    self.resume,
                    checkpointed_send_iv_next,
                    restored_send_iv_next,
                    forward_jump,
                );
            }
            SameSpiOutboundIvResume::Unspecified | SameSpiOutboundIvResume::IkeRandomIv { .. } => {
                hasher.update(b"opc-ipsec-lb/repin-transition/v2");
                hash_request_prefix(&mut hasher, self);
                hash_resume_v2(&mut hasher, self.resume);
            }
        }
        OwnershipTransitionFingerprint(hasher.finalize().into())
    }
}

fn hash_request_prefix(hasher: &mut Sha256, request: &RePinRequest) {
    hasher.update(request.transition_id.get().to_be_bytes());
    hasher.update(request.previous_fence.get().to_be_bytes());
    hash_sa(hasher, request.sa);
    hash_bytes(hasher, request.previous_owner.as_str().as_bytes());
    hash_bytes(hasher, request.new_owner.as_str().as_bytes());
    hasher.update(request.rule.shard.get().to_be_bytes());
    hasher.update(request.rule.owner.get().to_be_bytes());
    hash_steer_key(hasher, request.rule.key);
}

/// Ownership fence mutation request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OwnershipFenceRequest {
    /// SA being fenced.
    pub sa: SaId,
    /// Stable identity reused only for retries of this transition.
    pub transition_id: OwnershipTransitionId,
    /// Canonical binding to the complete re-pin request.
    pub fingerprint: OwnershipTransitionFingerprint,
    /// Exact predecessor fence that must still be authoritative.
    pub previous_fence: OwnershipFence,
    /// Owner expected before the transition.
    pub previous_owner: ClusterNode,
    /// New owner that receives the monotonic fence.
    pub new_owner: ClusterNode,
}

/// Successful ownership fence grant.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OwnershipFenceGrant {
    /// SA that was fenced.
    pub sa: SaId,
    /// Transition identity committed with the ownership record.
    pub transition_id: OwnershipTransitionId,
    /// Fingerprint committed with the transition.
    pub fingerprint: OwnershipTransitionFingerprint,
    /// Owner holding the granted fence.
    pub owner: ClusterNode,
    /// Monotonic fence token.
    pub fence: OwnershipFence,
}

/// Evidence presented when resuming work after ownership was committed.
///
/// The fields are construction-private because only a coordinator that has
/// checked a matching fence grant may issue this proof. The proof is still
/// treated as untrusted on retry: [`OwnershipFencer::validate_retry_proof`]
/// must match its SA, owner, and exact fence against authoritative state.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OwnershipRetryProof {
    sa: SaId,
    transition_id: OwnershipTransitionId,
    fingerprint: OwnershipTransitionFingerprint,
    owner: ClusterNode,
    fence: OwnershipFence,
}

impl OwnershipRetryProof {
    pub(crate) fn from_grant(grant: &OwnershipFenceGrant) -> Self {
        Self {
            sa: grant.sa,
            transition_id: grant.transition_id,
            fingerprint: grant.fingerprint,
            owner: grant.owner.clone(),
            fence: grant.fence,
        }
    }

    /// Return the SA covered by this retry proof.
    #[must_use]
    pub const fn sa(&self) -> SaId {
        self.sa
    }

    /// Return the ownership transition covered by this proof.
    #[must_use]
    pub const fn transition_id(&self) -> OwnershipTransitionId {
        self.transition_id
    }

    /// Return the complete request fingerprint covered by this proof.
    #[must_use]
    pub const fn fingerprint(&self) -> OwnershipTransitionFingerprint {
        self.fingerprint
    }

    /// Return the owner that must still hold the authoritative fence.
    #[must_use]
    pub fn owner(&self) -> &ClusterNode {
        &self.owner
    }

    /// Return the exact committed fence covered by this proof.
    #[must_use]
    pub const fn fence(&self) -> OwnershipFence {
        self.fence
    }
}

/// Audit event kind emitted by the re-pin coordinator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RePinAuditEventKind {
    /// A validated re-pin attempt is about to mutate ownership.
    Attempt,
    /// Ownership was fenced to the new owner.
    Fenced,
    /// Steering override was installed.
    SteeringInstalled,
    /// Re-pin failed before a verified ownership grant was available.
    ///
    /// Recoverable post-commit failures are returned immediately as
    /// [`RePinPartialFailure`] and deliberately do not wait on best-effort
    /// failure auditing, which could strand the retry state.
    Failed,
}

/// Redaction-safe re-pin audit event.
#[derive(Clone, PartialEq, Eq)]
pub struct RePinAuditEvent {
    /// Event kind.
    pub kind: RePinAuditEventKind,
    /// SA being re-pinned.
    pub sa: SaId,
    /// Stable transition correlation identity.
    ///
    /// This field is not an idempotency key by itself or when paired only with
    /// [`RePinAuditEventKind`]; sinks deduplicate the complete event so distinct
    /// failed attempts retain their failure codes.
    pub transition_id: OwnershipTransitionId,
    /// Previous owner.
    pub previous_owner: ClusterNode,
    /// New owner.
    pub new_owner: ClusterNode,
    /// Fence token when one has been granted.
    pub fence: Option<OwnershipFence>,
    /// This is deliberately false for coordinator-emitted events. Packet-flow
    /// evidence must be injected separately by the lab/product dataplane.
    pub forwarding_proven: bool,
    /// Stable failure code for failed attempts.
    pub failure_code: Option<&'static str>,
}

impl fmt::Debug for RePinAuditEvent {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("RePinAuditEvent")
            .field("kind", &self.kind)
            .field("sa", &"[redacted]")
            .field("transition_id", &"[redacted]")
            .field("previous_owner", &"[redacted]")
            .field("new_owner", &"[redacted]")
            .field("fence_present", &self.fence.is_some())
            .field("forwarding_proven", &self.forwarding_proven)
            .field("failure_code", &self.failure_code)
            .finish()
    }
}

impl RePinAuditEvent {
    fn attempt(request: &RePinRequest) -> Self {
        Self {
            kind: RePinAuditEventKind::Attempt,
            sa: request.sa,
            transition_id: request.transition_id,
            previous_owner: request.previous_owner.clone(),
            new_owner: request.new_owner.clone(),
            fence: None,
            forwarding_proven: false,
            failure_code: None,
        }
    }

    fn fenced(request: &RePinRequest, fence: OwnershipFence) -> Self {
        Self {
            kind: RePinAuditEventKind::Fenced,
            sa: request.sa,
            transition_id: request.transition_id,
            previous_owner: request.previous_owner.clone(),
            new_owner: request.new_owner.clone(),
            fence: Some(fence),
            forwarding_proven: false,
            failure_code: None,
        }
    }

    fn steering_installed(request: &RePinRequest, fence: OwnershipFence) -> Self {
        Self {
            kind: RePinAuditEventKind::SteeringInstalled,
            sa: request.sa,
            transition_id: request.transition_id,
            previous_owner: request.previous_owner.clone(),
            new_owner: request.new_owner.clone(),
            fence: Some(fence),
            forwarding_proven: false,
            failure_code: None,
        }
    }

    fn failed(request: &RePinRequest, fence: Option<OwnershipFence>, error: &IpsecLbError) -> Self {
        Self {
            kind: RePinAuditEventKind::Failed,
            sa: request.sa,
            transition_id: request.transition_id,
            previous_owner: request.previous_owner.clone(),
            new_owner: request.new_owner.clone(),
            fence,
            forwarding_proven: false,
            failure_code: Some(error_code(error)),
        }
    }
}

/// Injected proof that forwarded packets were observed after a re-pin.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ForwardingProof {
    sa: SaId,
    fence: OwnershipFence,
    observed_packets: NonZeroU64,
}

impl ForwardingProof {
    /// Build a packet-flow proof from an external dataplane observation.
    pub fn new(
        sa: SaId,
        fence: OwnershipFence,
        observed_packets: u64,
    ) -> Result<Self, IpsecLbError> {
        let Some(observed_packets) = NonZeroU64::new(observed_packets) else {
            return Err(IpsecLbError::forwarding_proof_rejected(
                "observed packet count must be non-zero",
            ));
        };
        Ok(Self {
            sa,
            fence,
            observed_packets,
        })
    }

    /// Return the SA covered by this proof.
    #[must_use]
    pub const fn sa(self) -> SaId {
        self.sa
    }

    /// Return the fence covered by this proof.
    #[must_use]
    pub const fn fence(self) -> OwnershipFence {
        self.fence
    }

    /// Return observed packet count.
    #[must_use]
    pub const fn observed_packets(self) -> u64 {
        self.observed_packets.get()
    }
}

/// Result of a fenced re-pin and steering install.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct RePinOutcome {
    sa: SaId,
    fence: OwnershipFence,
    rule: SteeringRule,
    forwarding_proven: bool,
}

impl RePinOutcome {
    fn new(sa: SaId, fence: OwnershipFence, rule: SteeringRule) -> Self {
        Self {
            sa,
            fence,
            rule,
            forwarding_proven: false,
        }
    }

    /// Return the ownership fence used for this re-pin.
    #[must_use]
    pub const fn fence(self) -> OwnershipFence {
        self.fence
    }

    /// Return the steering rule installed for this re-pin.
    #[must_use]
    pub const fn rule(self) -> SteeringRule {
        self.rule
    }

    /// True only after an external forwarding proof has been injected.
    #[must_use]
    pub const fn forwarding_proven(self) -> bool {
        self.forwarding_proven
    }

    /// Attach external dataplane proof to the outcome.
    pub fn with_forwarding_proof(mut self, proof: ForwardingProof) -> Result<Self, IpsecLbError> {
        if proof.sa != self.sa {
            return Err(IpsecLbError::forwarding_proof_rejected(
                "proof SA does not match re-pin outcome",
            ));
        }
        if proof.fence != self.fence {
            return Err(IpsecLbError::forwarding_proof_rejected(
                "proof fence does not match re-pin outcome",
            ));
        }
        self.forwarding_proven = true;
        Ok(self)
    }
}

/// First incomplete operation after an authoritative ownership commit.
///
/// Retry resumes at this exact stage. Earlier successful stages are never
/// repeated, so a final audit retry cannot reinstall an already-active rule.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RePinRetryStage {
    /// Record the audit event that ownership was fenced.
    FencedAudit,
    /// Install the steering override.
    SteeringInstall,
    /// Record the audit event that steering was installed.
    SteeringAudit,
}

/// Recoverable state returned when ownership committed but re-pin did not
/// finish.
///
/// Construction is private to prevent callers from selecting a later retry
/// stage and skipping a required side effect. Pass the value back to
/// [`RePinCoordinator::retry`] unchanged. The included ownership proof is
/// always validated by the fencer before retry performs an audit or steering
/// mutation. Callers that need cancellation safety should clone and retain
/// [`RePinPartialFailure::request`] before starting `retry`; replaying that
/// request through [`RePinCoordinator::repin`] recovers the exact current
/// ownership grant before attempting another fence.
#[must_use]
#[derive(Debug, PartialEq, Eq)]
pub struct RePinPartialFailure {
    request: RePinRequest,
    retry_proof: OwnershipRetryProof,
    resume_at: RePinRetryStage,
    cause: IpsecLbError,
}

impl RePinPartialFailure {
    fn new(
        request: RePinRequest,
        retry_proof: OwnershipRetryProof,
        resume_at: RePinRetryStage,
        cause: IpsecLbError,
    ) -> Self {
        Self {
            request,
            retry_proof,
            resume_at,
            cause,
        }
    }

    /// Return the operation that retry will attempt first.
    #[must_use]
    pub const fn resume_at(&self) -> RePinRetryStage {
        self.resume_at
    }

    /// Return the error that interrupted the latest attempt.
    #[must_use]
    pub const fn cause(&self) -> &IpsecLbError {
        &self.cause
    }

    /// Return the committed ownership fence.
    #[must_use]
    pub const fn fence(&self) -> OwnershipFence {
        self.retry_proof.fence()
    }

    /// Return the proof that retry will validate against authoritative state.
    #[must_use]
    pub const fn retry_proof(&self) -> &OwnershipRetryProof {
        &self.retry_proof
    }

    /// Return the original request for explicit cancellation-safe retention.
    ///
    /// The partial itself remains single-use. Clone this request before
    /// starting [`RePinCoordinator::retry`] when the retry future may be
    /// cancelled, then pass the retained clone to [`RePinCoordinator::repin`]
    /// to recover authoritative ownership state.
    #[must_use]
    pub const fn request(&self) -> &RePinRequest {
        &self.request
    }

    fn with_cause(mut self, cause: IpsecLbError) -> Self {
        self.cause = cause;
        self
    }
}

/// Failure returned by re-pin coordination.
#[derive(Debug, PartialEq, Eq, thiserror::Error)]
pub enum RePinError {
    /// No matching, trustworthy ownership grant was available to issue a
    /// retry proof.
    ///
    /// This includes a malformed grant returned by a fencer. Such a fencer may
    /// have changed external state, but the coordinator cannot safely trust or
    /// issue a proof for that unverified result. A retained request may be
    /// replayed: `repin` always performs authoritative recovery before trying
    /// another ownership mutation.
    #[error("re-pin failed before a verifiable ownership commit: {0}")]
    BeforeOwnershipCommit(#[source] IpsecLbError),
    /// Ownership committed at the carried fence and remaining work can be
    /// resumed through [`RePinCoordinator::retry`].
    #[error("re-pin is incomplete after ownership commit")]
    AfterOwnershipCommit(Box<RePinPartialFailure>),
}

impl RePinError {
    /// Return the underlying port or validation error.
    #[must_use]
    pub const fn cause(&self) -> &IpsecLbError {
        match self {
            Self::BeforeOwnershipCommit(cause) => cause,
            Self::AfterOwnershipCommit(partial) => partial.cause(),
        }
    }

    /// Consume the error and return recoverable post-commit state, if any.
    #[must_use]
    pub fn into_partial(self) -> Option<RePinPartialFailure> {
        match self {
            Self::BeforeOwnershipCommit(_) => None,
            Self::AfterOwnershipCommit(partial) => Some(*partial),
        }
    }
}

/// Coordinates audited, fenced re-pin before steering override installation.
#[derive(Debug, Clone)]
pub struct RePinCoordinator<B, F, O, A> {
    steering: B,
    fencer: F,
    ownership: O,
    audit: A,
}

impl<B, F, O, A> RePinCoordinator<B, F, O, A>
where
    B: SteeringBackend,
    F: OwnershipFencer,
    O: OwnershipSource,
    A: RePinAuditSink,
{
    /// Build a coordinator from explicit ports.
    #[must_use]
    pub const fn new(steering: B, fencer: F, ownership: O, audit: A) -> Self {
        Self {
            steering,
            fencer,
            ownership,
            audit,
        }
    }

    /// Validate resume evidence and the target-shard binding, recover or fence
    /// ownership, audit the transition, and install the steering override.
    ///
    /// Recovery is checked before mutation, making a cloned request safe to
    /// replay when cancellation or an ambiguous fencer result may have hidden
    /// a committed grant. A recovered transition resumes at the fenced-audit
    /// stage with the exact current fence.
    pub async fn repin(&self, request: RePinRequest) -> Result<RePinOutcome, RePinError> {
        self.validate_pre_commit(&request)
            .await
            .map_err(RePinError::BeforeOwnershipCommit)?;

        let fence_request = OwnershipFenceRequest {
            sa: request.sa,
            transition_id: request.transition_id,
            fingerprint: request.ownership_fingerprint(),
            previous_fence: request.previous_fence,
            previous_owner: request.previous_owner.clone(),
            new_owner: request.new_owner.clone(),
        };
        match self.fencer.recover_fence_grant(&fence_request).await {
            Ok(Some(grant)) => return self.continue_from_grant(request, grant).await,
            Ok(None) => {}
            Err(error) => return Err(RePinError::BeforeOwnershipCommit(error)),
        }

        self.audit
            .record_repin(RePinAuditEvent::attempt(&request))
            .await
            .map_err(RePinError::BeforeOwnershipCommit)?;

        let grant = match self.fencer.fence_sa_owner(fence_request.clone()).await {
            Ok(grant) => grant,
            Err(error) => match self.fencer.recover_fence_grant(&fence_request).await {
                Ok(Some(grant)) => grant,
                Ok(None) => {
                    record_failure(&self.audit, &request, None, &error).await;
                    return Err(RePinError::BeforeOwnershipCommit(error));
                }
                Err(recovery_error) => {
                    record_failure(&self.audit, &request, None, &recovery_error).await;
                    return Err(RePinError::BeforeOwnershipCommit(recovery_error));
                }
            },
        };

        self.continue_from_grant(request, grant).await
    }

    async fn continue_from_grant(
        &self,
        request: RePinRequest,
        grant: OwnershipFenceGrant,
    ) -> Result<RePinOutcome, RePinError> {
        // Do not trust the fencer port blindly: a grant for a different SA or a
        // different owner would install a steering override toward the wrong
        // node. Reject it before any steering mutation.
        validate_grant_matches(&request, &grant).map_err(RePinError::BeforeOwnershipCommit)?;

        let retry_proof = OwnershipRetryProof::from_grant(&grant);
        // A shape-matching successful grant is post-commit by the fencer port
        // contract, but it is not enough to emit an authoritative Fenced audit
        // event. Confirm its exact store-backed fence first. Preserve the
        // single-use retry state on a transient or stale read: retry validates
        // again before any side effect, while a forged proof remains inert.
        if let Err(error) = self.fencer.validate_retry_proof(&retry_proof).await {
            return Err(RePinError::AfterOwnershipCommit(Box::new(
                RePinPartialFailure::new(request, retry_proof, RePinRetryStage::FencedAudit, error),
            )));
        }
        self.continue_committed(request, retry_proof, RePinRetryStage::FencedAudit)
            .await
    }

    /// Resume a re-pin that stopped after ownership was authoritatively
    /// committed.
    ///
    /// Static safety checks and the target-shard binding are checked again.
    /// Before any audit or steering side effect, the fencer must also confirm
    /// that the proof's exact SA, owner, and fence are still authoritative.
    pub async fn retry(&self, partial: RePinPartialFailure) -> Result<RePinOutcome, RePinError> {
        if let Err(error) = self.validate_pre_commit(&partial.request).await {
            return Err(RePinError::AfterOwnershipCommit(Box::new(
                partial.with_cause(error),
            )));
        }

        if partial.retry_proof.sa != partial.request.sa
            || partial.retry_proof.transition_id != partial.request.transition_id
            || partial.retry_proof.fingerprint != partial.request.ownership_fingerprint()
            || partial.retry_proof.owner != partial.request.new_owner
        {
            return Err(RePinError::AfterOwnershipCommit(Box::new(
                partial.with_cause(IpsecLbError::ownership_conflict(
                    "retry proof does not match the original SA and new owner",
                )),
            )));
        }

        // Steering-install resumes validate the proof immediately beside that
        // mutation below. The audit stages need validation here so no audit
        // side effect can occur under a stale or forged proof.
        if partial.resume_at != RePinRetryStage::SteeringInstall {
            if let Err(error) = self.fencer.validate_retry_proof(&partial.retry_proof).await {
                return Err(RePinError::AfterOwnershipCommit(Box::new(
                    partial.with_cause(error),
                )));
            }
        }

        self.continue_committed(partial.request, partial.retry_proof, partial.resume_at)
            .await
    }

    /// Revalidate and idempotently reconcile one previously completed re-pin.
    ///
    /// This boundary is deliberately read-only with respect to ownership: it
    /// requires recovery of the exact committed transition, verifies its
    /// owner, fence, transition ID, and complete request fingerprint, and then
    /// repeats the exact steering install under the backend's idempotency
    /// contract. It never calls [`OwnershipFencer::fence_sa_owner`] and emits no
    /// new transition audit events. Session-level recovery uses this before
    /// mutating a later SA and again before reporting terminal success, which
    /// detects direct per-SA coordinator use that displaced an earlier prefix.
    pub async fn reconcile_committed(
        &self,
        request: &RePinRequest,
        expected_fence: OwnershipFence,
    ) -> Result<RePinOutcome, IpsecLbError> {
        let outcome = self.validate_committed(request, expected_fence).await?;
        self.steering.install_rule(request.rule).await?;
        Ok(outcome)
    }

    /// Validate one previously completed re-pin without any mutation.
    ///
    /// This performs authoritative recovery and exact retry-proof validation
    /// for the owner, fence, transition ID, and complete request fingerprint,
    /// then rechecks the target shard owner. It never fences ownership,
    /// installs or removes steering, or records an audit event. Session-level
    /// recovery calls this for the whole completed prefix only after every
    /// steering repair has finished, establishing a mutation-free validation
    /// sweep before a later SA mutation or terminal result.
    pub async fn validate_committed(
        &self,
        request: &RePinRequest,
        expected_fence: OwnershipFence,
    ) -> Result<RePinOutcome, IpsecLbError> {
        self.validate_pre_commit(request).await?;
        let fence_request = OwnershipFenceRequest {
            sa: request.sa,
            transition_id: request.transition_id,
            fingerprint: request.ownership_fingerprint(),
            previous_fence: request.previous_fence,
            previous_owner: request.previous_owner.clone(),
            new_owner: request.new_owner.clone(),
        };
        let grant = self
            .fencer
            .recover_fence_grant(&fence_request)
            .await?
            .ok_or_else(|| {
                IpsecLbError::ownership_conflict(
                    "completed re-pin has no exact authoritative ownership grant",
                )
            })?;
        validate_grant_matches(request, &grant)?;
        if grant.fence != expected_fence {
            return Err(IpsecLbError::ownership_conflict(
                "completed re-pin fence does not match durable progress",
            ));
        }
        let proof = OwnershipRetryProof::from_grant(&grant);
        self.fencer.validate_retry_proof(&proof).await?;
        self.validate_target_owner(request).await?;
        Ok(RePinOutcome::new(request.sa, grant.fence, request.rule))
    }

    async fn validate_pre_commit(&self, request: &RePinRequest) -> Result<(), IpsecLbError> {
        validate_request(request)?;
        request.resume.validate_for_repin(request.sa)?;

        self.validate_target_owner(request).await
    }

    async fn validate_target_owner(&self, request: &RePinRequest) -> Result<(), IpsecLbError> {
        match self.ownership.shard_owner(request.rule.owner).await? {
            Some(owner) if owner == request.new_owner => Ok(()),
            Some(_) => Err(IpsecLbError::ownership_conflict(
                "steering target shard is not owned by the requested new owner",
            )),
            None => Err(IpsecLbError::ownership_conflict(
                "steering target shard has no authoritative owner",
            )),
        }
    }

    async fn continue_committed(
        &self,
        request: RePinRequest,
        retry_proof: OwnershipRetryProof,
        resume_at: RePinRetryStage,
    ) -> Result<RePinOutcome, RePinError> {
        let fence = retry_proof.fence;

        if resume_at == RePinRetryStage::FencedAudit {
            if let Err(error) = self
                .audit
                .record_repin(RePinAuditEvent::fenced(&request, fence))
                .await
            {
                return Err(RePinError::AfterOwnershipCommit(Box::new(
                    RePinPartialFailure::new(
                        request,
                        retry_proof,
                        RePinRetryStage::FencedAudit,
                        error,
                    ),
                )));
            }
        }

        if matches!(
            resume_at,
            RePinRetryStage::FencedAudit | RePinRetryStage::SteeringInstall
        ) {
            // The initial target-owner read precedes multiple awaited effects.
            // Re-read it and the exact SA fence as late as the current ports
            // permit so a change during fencing/audit fails closed before the
            // steering mutation. Atomic cross-resource ordering still belongs
            // in a fence-aware steering backend.
            if let Err(error) = self.fencer.validate_retry_proof(&retry_proof).await {
                return Err(RePinError::AfterOwnershipCommit(Box::new(
                    RePinPartialFailure::new(
                        request,
                        retry_proof,
                        RePinRetryStage::SteeringInstall,
                        error,
                    ),
                )));
            }
            // The ownership port cannot atomically bind shard and SA records,
            // so leave the target-owner snapshot as the last awaited check
            // before steering. A fence-aware backend is still required for a
            // strict cross-resource atomicity guarantee.
            if let Err(error) = self.validate_target_owner(&request).await {
                return Err(RePinError::AfterOwnershipCommit(Box::new(
                    RePinPartialFailure::new(
                        request,
                        retry_proof,
                        RePinRetryStage::SteeringInstall,
                        error,
                    ),
                )));
            }
            if let Err(error) = self.steering.install_rule(request.rule).await {
                return Err(RePinError::AfterOwnershipCommit(Box::new(
                    RePinPartialFailure::new(
                        request,
                        retry_proof,
                        RePinRetryStage::SteeringInstall,
                        error,
                    ),
                )));
            }
        }

        if let Err(error) = self
            .audit
            .record_repin(RePinAuditEvent::steering_installed(&request, fence))
            .await
        {
            return Err(RePinError::AfterOwnershipCommit(Box::new(
                RePinPartialFailure::new(
                    request,
                    retry_proof,
                    RePinRetryStage::SteeringAudit,
                    error,
                ),
            )));
        }

        Ok(RePinOutcome::new(request.sa, fence, request.rule))
    }
}

fn validate_grant_matches(
    request: &RePinRequest,
    grant: &OwnershipFenceGrant,
) -> Result<(), IpsecLbError> {
    if grant.sa != request.sa
        || grant.transition_id != request.transition_id
        || grant.fingerprint != request.ownership_fingerprint()
        || grant.owner != request.new_owner
    {
        return Err(IpsecLbError::ownership_conflict(
            "fence grant does not match the requested SA and new owner",
        ));
    }
    Ok(())
}

fn hash_bytes(hasher: &mut Sha256, bytes: &[u8]) {
    hasher.update((bytes.len() as u64).to_be_bytes());
    hasher.update(bytes);
}

fn hash_sa(hasher: &mut Sha256, sa: SaId) {
    match sa {
        SaId::Ike { responder_spi } => {
            hasher.update([1]);
            hasher.update(responder_spi.to_be_bytes());
        }
        SaId::Esp { spi } => {
            hasher.update([2]);
            hasher.update(spi.to_be_bytes());
        }
    }
}

fn hash_steer_key(hasher: &mut Sha256, key: SteerKey) {
    match key {
        SteerKey::IkeResponderSpi(spi) => {
            hasher.update([1]);
            hasher.update(spi.to_be_bytes());
        }
        SteerKey::IkeInit {
            initiator_spi,
            source_ip,
        } => {
            hasher.update([2]);
            hasher.update(initiator_spi.to_be_bytes());
            match source_ip {
                IpAddress::V4(octets) => {
                    hasher.update([4]);
                    hasher.update(octets);
                }
                IpAddress::V6(octets) => {
                    hasher.update([6]);
                    hasher.update(octets);
                }
            }
        }
        SteerKey::EspSpi(spi) => {
            hasher.update([3]);
            hasher.update(spi.to_be_bytes());
        }
    }
}

fn hash_counter_resume_v1(
    hasher: &mut Sha256,
    resume: SameSpiResume,
    checkpointed_send_iv_next: u64,
    restored_send_iv_next: u64,
    forward_jump: Option<SendIvForwardJump>,
) {
    hash_sa(hasher, resume.previous_sa);
    hash_sa(hasher, resume.resumed_sa);
    hasher.update(checkpointed_send_iv_next.to_be_bytes());
    hasher.update(restored_send_iv_next.to_be_bytes());
    hash_forward_jump(hasher, forward_jump);
    hash_anti_replay_and_key_source(hasher, resume);
}

fn hash_resume_v2(hasher: &mut Sha256, resume: SameSpiResume) {
    hash_sa(hasher, resume.previous_sa);
    hash_sa(hasher, resume.resumed_sa);
    match resume.outbound_iv {
        SameSpiOutboundIvResume::Unspecified => hasher.update([0]),
        SameSpiOutboundIvResume::CounterBased {
            checkpointed_send_iv_next,
            restored_send_iv_next,
            forward_jump,
        } => {
            hasher.update([1]);
            hasher.update(checkpointed_send_iv_next.to_be_bytes());
            hasher.update(restored_send_iv_next.to_be_bytes());
            hash_forward_jump(hasher, forward_jump);
        }
        SameSpiOutboundIvResume::IkeRandomIv { attestation } => {
            hasher.update([2]);
            match attestation {
                IkeRandomIvAttestation::FreshIndependentCsprngIvPerMessage => {
                    hasher.update([1]);
                }
            }
        }
    }
    hash_anti_replay_and_key_source(hasher, resume);
}

fn hash_forward_jump(hasher: &mut Sha256, forward_jump: Option<SendIvForwardJump>) {
    match forward_jump {
        None => hasher.update([0]),
        Some(jump) => {
            hasher.update([1]);
            hasher.update(jump.forward_jump.to_be_bytes());
            match jump.counter_mode {
                SendIvCounterMode::EspExtendedSequenceNumbers {
                    max_peer_sequence_lag,
                } => {
                    hasher.update([1]);
                    hasher.update(max_peer_sequence_lag.to_be_bytes());
                }
                SendIvCounterMode::IkeAeadExplicitIv64 => hasher.update([2]),
            }
        }
    }
}

fn hash_anti_replay_and_key_source(hasher: &mut Sha256, resume: SameSpiResume) {
    match resume.anti_replay {
        AntiReplayResume::ExactWindowRestore {
            checkpoint_highest_accepted,
            restored_highest_accepted,
        } => {
            hasher.update([1]);
            hasher.update(checkpoint_highest_accepted.to_be_bytes());
            hasher.update(restored_highest_accepted.to_be_bytes());
        }
        AntiReplayResume::BoundedReopening {
            checkpoint_highest_accepted,
            restored_highest_accepted,
            max_reopened_packets,
        } => {
            hasher.update([2]);
            hasher.update(checkpoint_highest_accepted.to_be_bytes());
            hasher.update(restored_highest_accepted.to_be_bytes());
            hasher.update(max_reopened_packets.to_be_bytes());
        }
    }
    hasher.update([match resume.key_source {
        ResumeKeySource::LiveMirrored => 1,
        ResumeKeySource::RekeyOrReattachFallback => 2,
        ResumeKeySource::PersistedKeyMaterial => 3,
    }]);
}

pub(crate) fn validate_request(request: &RePinRequest) -> Result<(), IpsecLbError> {
    if request.previous_owner == request.new_owner {
        return Err(IpsecLbError::invalid_config(
            "new_owner",
            "re-pin requires a different owner",
        ));
    }
    validate_sa_identifier(request.sa)?;
    match (request.sa, request.rule.key) {
        (SaId::Esp { spi }, SteerKey::EspSpi(rule_spi)) if spi == rule_spi => {}
        (SaId::Ike { responder_spi }, SteerKey::IkeResponderSpi(rule_responder_spi))
            if responder_spi == rule_responder_spi => {}
        _ => {
            return Err(IpsecLbError::invalid_config(
                "rule",
                "re-pin steering key must match the fenced SA protocol and SPI",
            ));
        }
    }
    Ok(())
}

pub(crate) fn validate_sa_identifier(sa: SaId) -> Result<(), IpsecLbError> {
    match sa {
        SaId::Esp { spi: 0 } => {
            return Err(IpsecLbError::invalid_config(
                "sa.spi",
                "ESP SPI must be non-zero",
            ));
        }
        SaId::Ike { responder_spi: 0 } => {
            return Err(IpsecLbError::invalid_config(
                "sa.responder_spi",
                "IKE responder SPI must be non-zero",
            ));
        }
        SaId::Esp { .. } | SaId::Ike { .. } => {}
    }
    Ok(())
}

async fn record_failure<A>(
    audit: &A,
    request: &RePinRequest,
    fence: Option<OwnershipFence>,
    error: &IpsecLbError,
) where
    A: RePinAuditSink,
{
    let _ = audit
        .record_repin(RePinAuditEvent::failed(request, fence, error))
        .await;
}

fn error_code(error: &IpsecLbError) -> &'static str {
    match error {
        IpsecLbError::InvalidSpiLayout { .. } => "invalid_spi_layout",
        IpsecLbError::UnknownShard => "unknown_shard",
        IpsecLbError::EmptyShardSet => "empty_shard_set",
        IpsecLbError::DuplicateShard => "duplicate_shard",
        IpsecLbError::TagSpaceExhausted => "tag_space_exhausted",
        IpsecLbError::EntropyUnavailable => "entropy_unavailable",
        IpsecLbError::AllocationAttemptsExhausted => "allocation_attempts_exhausted",
        IpsecLbError::SpiOutOfRange => "spi_out_of_range",
        IpsecLbError::PacketRejected { .. } => "packet_rejected",
        IpsecLbError::Io { .. } => "io",
        IpsecLbError::InvalidConfig { .. } => "invalid_config",
        IpsecLbError::AdapterContractViolation { .. } => "adapter_contract_violation",
        IpsecLbError::Unsupported => "unsupported",
        IpsecLbError::AlreadyExists => "already_exists",
        IpsecLbError::NotFound => "not_found",
        IpsecLbError::OwnershipConflict { .. } => "ownership_conflict",
        IpsecLbError::ForwardingProofRejected { .. } => "forwarding_proof_rejected",
        IpsecLbError::UnsafeResume { .. } => "unsafe_resume",
        IpsecLbError::CookieRejected => "cookie_rejected",
        IpsecLbError::XdpKernelFloorNotMet { .. } => "xdp_kernel_floor_not_met",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::failover::SendIvCounterMode;

    const FORWARD_JUMP: u64 = crate::failover::MIN_SEND_IV_FORWARD_JUMP;
    const FROZEN_COUNTER_V1_FINGERPRINT: [u8; 32] = [
        0x7e, 0xeb, 0x23, 0x71, 0xb3, 0xea, 0xbc, 0x7d, 0x94, 0xf9, 0x2e, 0x41, 0x4c, 0xad, 0x9d,
        0xb3, 0x62, 0x2f, 0x10, 0x78, 0xa3, 0x20, 0x32, 0x8e, 0x81, 0xce, 0x8b, 0xd4, 0x09, 0x56,
        0x59, 0xcd,
    ];
    const FROZEN_RANDOM_IV_V2_FINGERPRINT: [u8; 32] = [
        0xcb, 0x74, 0x27, 0xfd, 0x0e, 0x4d, 0x66, 0xec, 0x4e, 0xc9, 0xad, 0xfb, 0xdc, 0xe1, 0x0a,
        0x18, 0xcf, 0x2f, 0xf2, 0x77, 0x5d, 0x13, 0x8b, 0x56, 0x1e, 0x80, 0x9c, 0xd9, 0x96, 0xfe,
        0xec, 0x48,
    ];

    fn valid_forward_jump(sa: SaId) -> SendIvForwardJump {
        SendIvForwardJump {
            forward_jump: FORWARD_JUMP,
            counter_mode: match sa {
                SaId::Esp { .. } => SendIvCounterMode::EspExtendedSequenceNumbers {
                    max_peer_sequence_lag: 0,
                },
                SaId::Ike { .. } => SendIvCounterMode::IkeAeadExplicitIv64,
            },
        }
    }

    fn counter_outbound_iv(
        checkpointed_send_iv_next: u64,
        restored_send_iv_next: u64,
        forward_jump: Option<SendIvForwardJump>,
    ) -> SameSpiOutboundIvResume {
        SameSpiOutboundIvResume::CounterBased {
            checkpointed_send_iv_next,
            restored_send_iv_next,
            forward_jump,
        }
    }

    fn valid_resume(sa: SaId, key_source: ResumeKeySource) -> SameSpiResume {
        SameSpiResume {
            previous_sa: sa,
            resumed_sa: sa,
            outbound_iv: counter_outbound_iv(10, 10 + FORWARD_JUMP, Some(valid_forward_jump(sa))),
            anti_replay: AntiReplayResume::ExactWindowRestore {
                checkpoint_highest_accepted: 20,
                restored_highest_accepted: 20,
            },
            key_source,
        }
    }

    fn valid_random_iv_ike_resume(key_source: ResumeKeySource) -> SameSpiResume {
        let sa = SaId::Ike { responder_spi: 1 };
        SameSpiResume {
            previous_sa: sa,
            resumed_sa: sa,
            outbound_iv: SameSpiOutboundIvResume::IkeRandomIv {
                attestation: IkeRandomIvAttestation::FreshIndependentCsprngIvPerMessage,
            },
            anti_replay: AntiReplayResume::ExactWindowRestore {
                checkpoint_highest_accepted: 20,
                restored_highest_accepted: 20,
            },
            key_source,
        }
    }

    fn frozen_counter_v1_request() -> RePinRequest {
        let sa = SaId::Esp { spi: 7 };
        RePinRequest {
            sa,
            transition_id: OwnershipTransitionId::new(7).unwrap(),
            previous_fence: OwnershipFence::new(1).unwrap(),
            previous_owner: ClusterNode::new("worker-a"),
            new_owner: ClusterNode::new("worker-b"),
            rule: SteeringRule {
                shard: crate::model::ShardId::new(1),
                owner: crate::model::ShardId::new(2),
                key: SteerKey::EspSpi(7),
            },
            resume: valid_resume(sa, ResumeKeySource::LiveMirrored),
        }
    }

    fn frozen_random_iv_v2_request() -> RePinRequest {
        let sa = SaId::Ike { responder_spi: 7 };
        RePinRequest {
            sa,
            transition_id: OwnershipTransitionId::new(7).unwrap(),
            previous_fence: OwnershipFence::new(1).unwrap(),
            previous_owner: ClusterNode::new("worker-a"),
            new_owner: ClusterNode::new("worker-b"),
            rule: SteeringRule {
                shard: crate::model::ShardId::new(1),
                owner: crate::model::ShardId::new(2),
                key: SteerKey::IkeResponderSpi(7),
            },
            resume: SameSpiResume {
                previous_sa: sa,
                resumed_sa: sa,
                outbound_iv: SameSpiOutboundIvResume::IkeRandomIv {
                    attestation: IkeRandomIvAttestation::FreshIndependentCsprngIvPerMessage,
                },
                anti_replay: AntiReplayResume::ExactWindowRestore {
                    checkpoint_highest_accepted: 20,
                    restored_highest_accepted: 20,
                },
                key_source: ResumeKeySource::LiveMirrored,
            },
        }
    }

    #[test]
    fn same_spi_resume_accepts_valid_jump_for_live_and_persisted_keys() {
        for sa in [SaId::Esp { spi: 1 }, SaId::Ike { responder_spi: 1 }] {
            for key_source in [
                ResumeKeySource::LiveMirrored,
                ResumeKeySource::PersistedKeyMaterial,
            ] {
                valid_resume(sa, key_source).validate_for_repin(sa).unwrap();
            }
        }
    }

    #[test]
    fn same_spi_resume_accepts_random_iv_ike_for_live_and_persisted_keys() {
        let sa = SaId::Ike { responder_spi: 1 };
        for key_source in [
            ResumeKeySource::LiveMirrored,
            ResumeKeySource::PersistedKeyMaterial,
        ] {
            valid_random_iv_ike_resume(key_source)
                .validate_for_repin(sa)
                .unwrap();
        }
    }

    #[test]
    fn counter_based_ownership_fingerprint_preserves_frozen_v1_encoding() {
        assert_eq!(
            frozen_counter_v1_request()
                .ownership_fingerprint()
                .as_bytes(),
            FROZEN_COUNTER_V1_FINGERPRINT
        );
    }

    #[test]
    fn random_iv_ownership_fingerprint_preserves_frozen_v2_encoding() {
        let request = frozen_random_iv_v2_request();
        validate_request(&request).unwrap();
        assert_eq!(
            request.ownership_fingerprint().as_bytes(),
            FROZEN_RANDOM_IV_V2_FINGERPRINT
        );
    }

    #[tokio::test]
    async fn migrated_counter_request_recovers_a_v1_committed_transition() {
        let request = frozen_counter_v1_request();
        let fencer = crate::mock::MockOwnershipFencer::new();
        fencer.set_owner(request.sa, request.previous_owner.clone());

        let committed = fencer
            .fence_sa_owner(OwnershipFenceRequest {
                sa: request.sa,
                transition_id: request.transition_id,
                fingerprint: OwnershipTransitionFingerprint::from_bytes(
                    FROZEN_COUNTER_V1_FINGERPRINT,
                ),
                previous_fence: request.previous_fence,
                previous_owner: request.previous_owner.clone(),
                new_owner: request.new_owner.clone(),
            })
            .await
            .unwrap();

        let steering = crate::mock::MockSteeringBackend::new();
        let ownership = crate::mock::MockOwnershipSource::default();
        ownership.set_shard_owner(request.rule.owner, request.new_owner.clone());
        let audit = crate::mock::MockRePinAuditSink::new();
        let coordinator =
            RePinCoordinator::new(steering.clone(), fencer.clone(), ownership, audit.clone());

        let outcome = coordinator.repin(request.clone()).await.unwrap();
        assert_eq!(outcome.fence(), committed.fence);
        assert_eq!(fencer.operations().len(), 1);
        assert_eq!(fencer.recovery_attempts(), 1);
        assert_eq!(
            steering.operations(),
            vec![crate::mock::MockSteeringOperation::Install(request.rule)]
        );
        assert_eq!(
            audit
                .events()
                .iter()
                .map(|event| event.kind)
                .collect::<Vec<_>>(),
            vec![
                RePinAuditEventKind::Fenced,
                RePinAuditEventKind::SteeringInstalled,
            ]
        );
    }

    #[test]
    fn ownership_fingerprint_binds_every_safety_critical_request_component() {
        let sa = SaId::Esp { spi: 7 };
        let base = frozen_counter_v1_request();
        let expected = base.ownership_fingerprint();
        assert_eq!(expected, base.clone().ownership_fingerprint());

        let mutations = [
            RePinRequest {
                sa: SaId::Esp { spi: 8 },
                ..base.clone()
            },
            RePinRequest {
                transition_id: OwnershipTransitionId::new(8).unwrap(),
                ..base.clone()
            },
            RePinRequest {
                previous_fence: OwnershipFence::new(4).unwrap(),
                ..base.clone()
            },
            RePinRequest {
                previous_owner: ClusterNode::new("worker-x"),
                ..base.clone()
            },
            RePinRequest {
                new_owner: ClusterNode::new("worker-y"),
                ..base.clone()
            },
            RePinRequest {
                rule: SteeringRule {
                    shard: crate::model::ShardId::new(4),
                    ..base.rule
                },
                ..base.clone()
            },
            RePinRequest {
                rule: SteeringRule {
                    owner: crate::model::ShardId::new(3),
                    ..base.rule
                },
                ..base.clone()
            },
            RePinRequest {
                rule: SteeringRule {
                    key: SteerKey::EspSpi(8),
                    ..base.rule
                },
                ..base.clone()
            },
            RePinRequest {
                resume: SameSpiResume {
                    previous_sa: SaId::Esp { spi: 8 },
                    ..base.resume
                },
                ..base.clone()
            },
            RePinRequest {
                resume: SameSpiResume {
                    resumed_sa: SaId::Esp { spi: 8 },
                    ..base.resume
                },
                ..base.clone()
            },
            RePinRequest {
                resume: SameSpiResume {
                    outbound_iv: counter_outbound_iv(
                        11,
                        11 + FORWARD_JUMP,
                        Some(valid_forward_jump(sa)),
                    ),
                    ..base.resume
                },
                ..base.clone()
            },
            RePinRequest {
                resume: SameSpiResume {
                    outbound_iv: counter_outbound_iv(10, 10 + FORWARD_JUMP, None),
                    ..base.resume
                },
                ..base.clone()
            },
            RePinRequest {
                resume: SameSpiResume {
                    outbound_iv: counter_outbound_iv(
                        10,
                        11 + FORWARD_JUMP,
                        Some(SendIvForwardJump {
                            forward_jump: FORWARD_JUMP + 1,
                            counter_mode: SendIvCounterMode::EspExtendedSequenceNumbers {
                                max_peer_sequence_lag: 0,
                            },
                        }),
                    ),
                    ..base.resume
                },
                ..base.clone()
            },
            RePinRequest {
                resume: SameSpiResume {
                    outbound_iv: counter_outbound_iv(
                        10,
                        10 + FORWARD_JUMP,
                        Some(SendIvForwardJump {
                            forward_jump: FORWARD_JUMP,
                            counter_mode: SendIvCounterMode::EspExtendedSequenceNumbers {
                                max_peer_sequence_lag: 1,
                            },
                        }),
                    ),
                    ..base.resume
                },
                ..base.clone()
            },
            RePinRequest {
                resume: SameSpiResume {
                    outbound_iv: counter_outbound_iv(
                        10,
                        10 + FORWARD_JUMP,
                        Some(SendIvForwardJump {
                            forward_jump: FORWARD_JUMP,
                            counter_mode: SendIvCounterMode::IkeAeadExplicitIv64,
                        }),
                    ),
                    ..base.resume
                },
                ..base.clone()
            },
            RePinRequest {
                resume: SameSpiResume {
                    outbound_iv: SameSpiOutboundIvResume::IkeRandomIv {
                        attestation: IkeRandomIvAttestation::FreshIndependentCsprngIvPerMessage,
                    },
                    ..base.resume
                },
                ..base.clone()
            },
            RePinRequest {
                resume: SameSpiResume {
                    outbound_iv: SameSpiOutboundIvResume::Unspecified,
                    ..base.resume
                },
                ..base.clone()
            },
            RePinRequest {
                resume: SameSpiResume {
                    anti_replay: AntiReplayResume::ExactWindowRestore {
                        checkpoint_highest_accepted: 21,
                        restored_highest_accepted: 21,
                    },
                    ..base.resume
                },
                ..base.clone()
            },
            RePinRequest {
                resume: SameSpiResume {
                    anti_replay: AntiReplayResume::BoundedReopening {
                        checkpoint_highest_accepted: 20,
                        restored_highest_accepted: 20,
                        max_reopened_packets: 64,
                    },
                    ..base.resume
                },
                ..base.clone()
            },
            RePinRequest {
                resume: SameSpiResume {
                    key_source: ResumeKeySource::PersistedKeyMaterial,
                    ..base.resume
                },
                ..base.clone()
            },
        ];

        for mutation in mutations {
            assert_ne!(expected, mutation.ownership_fingerprint());
        }
    }

    #[test]
    fn ownership_fingerprint_distinguishes_valid_ike_counter_and_random_iv_modes() {
        let sa = SaId::Ike { responder_spi: 1 };
        let counter = RePinRequest {
            sa,
            transition_id: OwnershipTransitionId::new(9).unwrap(),
            previous_fence: OwnershipFence::new(3).unwrap(),
            previous_owner: ClusterNode::new("worker-a"),
            new_owner: ClusterNode::new("worker-b"),
            rule: SteeringRule {
                shard: crate::model::ShardId::new(1),
                owner: crate::model::ShardId::new(2),
                key: SteerKey::IkeResponderSpi(1),
            },
            resume: valid_resume(sa, ResumeKeySource::PersistedKeyMaterial),
        };
        let random_iv = RePinRequest {
            resume: valid_random_iv_ike_resume(ResumeKeySource::PersistedKeyMaterial),
            ..counter.clone()
        };

        validate_request(&counter).unwrap();
        validate_request(&random_iv).unwrap();
        assert_ne!(
            counter.ownership_fingerprint(),
            random_iv.ownership_fingerprint()
        );
    }

    #[test]
    fn ownership_transition_id_rejects_zero() {
        assert!(matches!(
            OwnershipTransitionId::new(0),
            Err(IpsecLbError::InvalidConfig {
                field: "transition_id",
                ..
            })
        ));
    }

    #[test]
    fn same_spi_resume_rejects_zero_sa_identifiers_directly() {
        for sa in [SaId::Esp { spi: 0 }, SaId::Ike { responder_spi: 0 }] {
            assert!(matches!(
                valid_resume(sa, ResumeKeySource::LiveMirrored).validate_for_repin(sa),
                Err(IpsecLbError::InvalidConfig { .. })
            ));
        }
    }

    #[test]
    fn same_spi_resume_rejects_every_malformed_forward_jump_shape() {
        let sa = SaId::Esp { spi: 1 };

        for key_source in [
            ResumeKeySource::LiveMirrored,
            ResumeKeySource::PersistedKeyMaterial,
        ] {
            let mut missing = valid_resume(sa, key_source);
            missing.outbound_iv = counter_outbound_iv(10, 10 + FORWARD_JUMP, None);
            assert!(matches!(
                missing.validate_for_repin(sa),
                Err(IpsecLbError::UnsafeResume { .. })
            ));
        }

        let mut below_floor = valid_resume(sa, ResumeKeySource::PersistedKeyMaterial);
        below_floor.outbound_iv = counter_outbound_iv(
            10,
            10 + FORWARD_JUMP - 1,
            Some(SendIvForwardJump {
                forward_jump: FORWARD_JUMP - 1,
                counter_mode: SendIvCounterMode::EspExtendedSequenceNumbers {
                    max_peer_sequence_lag: 0,
                },
            }),
        );
        assert!(matches!(
            below_floor.validate_for_repin(sa),
            Err(IpsecLbError::UnsafeResume { .. })
        ));

        let mut wrong_protocol = valid_resume(sa, ResumeKeySource::LiveMirrored);
        wrong_protocol.outbound_iv = counter_outbound_iv(
            10,
            10 + FORWARD_JUMP,
            Some(SendIvForwardJump {
                forward_jump: FORWARD_JUMP,
                counter_mode: SendIvCounterMode::IkeAeadExplicitIv64,
            }),
        );
        assert!(matches!(
            wrong_protocol.validate_for_repin(sa),
            Err(IpsecLbError::UnsafeResume { .. })
        ));

        let mut mismatch = valid_resume(sa, ResumeKeySource::PersistedKeyMaterial);
        mismatch.outbound_iv =
            counter_outbound_iv(10, 10 + FORWARD_JUMP - 1, Some(valid_forward_jump(sa)));
        assert!(matches!(
            mismatch.validate_for_repin(sa),
            Err(IpsecLbError::UnsafeResume { .. })
        ));

        let mut exhausted = valid_resume(sa, ResumeKeySource::PersistedKeyMaterial);
        exhausted.outbound_iv = counter_outbound_iv(
            u64::MAX - FORWARD_JUMP + 1,
            u64::MAX,
            Some(valid_forward_jump(sa)),
        );
        assert!(matches!(
            exhausted.validate_for_repin(sa),
            Err(IpsecLbError::UnsafeResume { .. })
        ));

        let fallback = valid_resume(sa, ResumeKeySource::RekeyOrReattachFallback);
        assert!(matches!(
            fallback.validate_for_repin(sa),
            Err(IpsecLbError::UnsafeResume { .. })
        ));
    }

    #[test]
    fn same_spi_resume_accepts_matching_esp_and_ike_counter_modes_only() {
        let esp = SaId::Esp { spi: 1 };
        let ike = SaId::Ike { responder_spi: 7 };
        valid_resume(esp, ResumeKeySource::LiveMirrored)
            .validate_for_repin(esp)
            .unwrap();
        valid_resume(ike, ResumeKeySource::LiveMirrored)
            .validate_for_repin(ike)
            .unwrap();

        let mut esp_with_ike_counter = valid_resume(esp, ResumeKeySource::LiveMirrored);
        esp_with_ike_counter.outbound_iv = counter_outbound_iv(
            10,
            10 + FORWARD_JUMP,
            Some(SendIvForwardJump {
                forward_jump: FORWARD_JUMP,
                counter_mode: SendIvCounterMode::IkeAeadExplicitIv64,
            }),
        );
        assert!(matches!(
            esp_with_ike_counter.validate_for_repin(esp),
            Err(IpsecLbError::UnsafeResume { .. })
        ));

        let mut ike_with_esp_counter = valid_resume(ike, ResumeKeySource::LiveMirrored);
        ike_with_esp_counter.outbound_iv = counter_outbound_iv(
            10,
            10 + FORWARD_JUMP,
            Some(SendIvForwardJump {
                forward_jump: FORWARD_JUMP,
                counter_mode: SendIvCounterMode::EspExtendedSequenceNumbers {
                    max_peer_sequence_lag: 0,
                },
            }),
        );
        assert!(matches!(
            ike_with_esp_counter.validate_for_repin(ike),
            Err(IpsecLbError::UnsafeResume { .. })
        ));
    }

    #[test]
    fn same_spi_resume_random_iv_mode_rejects_esp_and_unspecified_evidence() {
        let ike = SaId::Ike { responder_spi: 1 };
        let esp = SaId::Esp { spi: 1 };

        let esp_random_iv = SameSpiResume {
            previous_sa: esp,
            resumed_sa: esp,
            outbound_iv: SameSpiOutboundIvResume::IkeRandomIv {
                attestation: IkeRandomIvAttestation::FreshIndependentCsprngIvPerMessage,
            },
            anti_replay: AntiReplayResume::ExactWindowRestore {
                checkpoint_highest_accepted: 20,
                restored_highest_accepted: 20,
            },
            key_source: ResumeKeySource::LiveMirrored,
        };
        assert!(matches!(
            esp_random_iv.validate_for_repin(esp),
            Err(IpsecLbError::UnsafeResume { .. })
        ));

        for sa in [ike, esp] {
            let mut unspecified = valid_resume(sa, ResumeKeySource::PersistedKeyMaterial);
            unspecified.outbound_iv = SameSpiOutboundIvResume::Unspecified;
            assert!(matches!(
                unspecified.validate_for_repin(sa),
                Err(IpsecLbError::UnsafeResume { .. })
            ));
        }
    }

    #[test]
    fn outbound_iv_resume_rejections_do_not_expose_sa_or_counter_values() {
        let sa = SaId::Ike {
            responder_spi: 0x1122_3344_5566_7788,
        };
        let evidence = SameSpiResume {
            previous_sa: sa,
            resumed_sa: sa,
            outbound_iv: SameSpiOutboundIvResume::CounterBased {
                checkpointed_send_iv_next: 987_654_321,
                restored_send_iv_next: 1_234_567_890,
                forward_jump: None,
            },
            anti_replay: AntiReplayResume::ExactWindowRestore {
                checkpoint_highest_accepted: 20,
                restored_highest_accepted: 20,
            },
            key_source: ResumeKeySource::PersistedKeyMaterial,
        };
        let error = evidence.validate_for_repin(sa).unwrap_err();
        let rendered = format!("{error:?} {error}");

        for forbidden in [
            "1122334455667788",
            "1234605616436508552",
            "987654321",
            "1234567890",
        ] {
            assert!(!rendered.contains(forbidden));
        }
    }

    #[test]
    fn same_spi_resume_random_iv_mode_keeps_common_safety_evidence_mandatory() {
        let sa = SaId::Ike { responder_spi: 1 };

        let fallback = valid_random_iv_ike_resume(ResumeKeySource::RekeyOrReattachFallback);
        assert!(matches!(
            fallback.validate_for_repin(sa),
            Err(IpsecLbError::UnsafeResume { .. })
        ));

        let mut identity_mismatch =
            valid_random_iv_ike_resume(ResumeKeySource::PersistedKeyMaterial);
        identity_mismatch.resumed_sa = SaId::Ike { responder_spi: 2 };
        assert!(matches!(
            identity_mismatch.validate_for_repin(sa),
            Err(IpsecLbError::UnsafeResume { .. })
        ));

        let mut replay_rollback = valid_random_iv_ike_resume(ResumeKeySource::LiveMirrored);
        replay_rollback.anti_replay = AntiReplayResume::ExactWindowRestore {
            checkpoint_highest_accepted: 20,
            restored_highest_accepted: 19,
        };
        assert!(matches!(
            replay_rollback.validate_for_repin(sa),
            Err(IpsecLbError::UnsafeResume { .. })
        ));
    }

    #[test]
    fn same_spi_resume_rejects_replay_checkpoint_rollback() {
        let sa = SaId::Esp { spi: 1 };
        let mut replay_rollback = valid_resume(sa, ResumeKeySource::LiveMirrored);
        replay_rollback.anti_replay = AntiReplayResume::ExactWindowRestore {
            checkpoint_highest_accepted: 20,
            restored_highest_accepted: 19,
        };
        assert!(matches!(
            replay_rollback.validate_for_repin(sa),
            Err(IpsecLbError::UnsafeResume { .. })
        ));
    }

    #[test]
    fn repin_request_requires_rule_key_to_match_fenced_sa_protocol_and_spi() {
        let sa = SaId::Esp { spi: 1 };
        let base = RePinRequest {
            sa,
            transition_id: OwnershipTransitionId::new(1).unwrap(),
            previous_fence: OwnershipFence::new(1).unwrap(),
            previous_owner: ClusterNode::new("worker-a"),
            new_owner: ClusterNode::new("worker-b"),
            rule: SteeringRule {
                shard: crate::model::ShardId::new(1),
                owner: crate::model::ShardId::new(2),
                key: SteerKey::EspSpi(1),
            },
            resume: valid_resume(sa, ResumeKeySource::LiveMirrored),
        };
        validate_request(&base).unwrap();

        let wrong_spi = RePinRequest {
            rule: SteeringRule {
                key: SteerKey::EspSpi(2),
                ..base.rule
            },
            ..base.clone()
        };
        assert!(matches!(
            validate_request(&wrong_spi),
            Err(IpsecLbError::InvalidConfig { field: "rule", .. })
        ));

        let ike_key = RePinRequest {
            rule: SteeringRule {
                key: SteerKey::IkeResponderSpi(1),
                ..base.rule
            },
            ..base
        };
        assert!(matches!(
            validate_request(&ike_key),
            Err(IpsecLbError::InvalidConfig { field: "rule", .. })
        ));

        let ike_sa = SaId::Ike { responder_spi: 7 };
        let ike_request = RePinRequest {
            sa: ike_sa,
            transition_id: OwnershipTransitionId::new(2).unwrap(),
            previous_fence: OwnershipFence::new(1).unwrap(),
            previous_owner: ClusterNode::new("worker-a"),
            new_owner: ClusterNode::new("worker-b"),
            rule: SteeringRule {
                shard: crate::model::ShardId::new(1),
                owner: crate::model::ShardId::new(2),
                key: SteerKey::IkeResponderSpi(7),
            },
            resume: valid_resume(ike_sa, ResumeKeySource::LiveMirrored),
        };
        validate_request(&ike_request).unwrap();

        let wrong_responder_spi = RePinRequest {
            rule: SteeringRule {
                key: SteerKey::IkeResponderSpi(8),
                ..ike_request.rule
            },
            ..ike_request
        };
        assert!(matches!(
            validate_request(&wrong_responder_spi),
            Err(IpsecLbError::InvalidConfig { field: "rule", .. })
        ));
    }

    #[test]
    fn forwarding_proof_must_match_sa_and_fence() {
        let sa = SaId::Esp { spi: 1 };
        let fence = OwnershipFence::new(7).unwrap();
        assert!(ForwardingProof::new(sa, fence, 0).is_err());

        let outcome = RePinOutcome::new(
            sa,
            fence,
            SteeringRule {
                shard: crate::model::ShardId::new(1),
                owner: crate::model::ShardId::new(2),
                key: crate::model::SteerKey::EspSpi(1),
            },
        );
        let wrong_sa = ForwardingProof::new(SaId::Esp { spi: 2 }, fence, 1).unwrap();
        assert!(matches!(
            outcome.with_forwarding_proof(wrong_sa).unwrap_err(),
            IpsecLbError::ForwardingProofRejected { .. }
        ));
    }
}
