apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - reference.openpacketcore.io
  resources:
  - sdkmanagednetworkfunctions
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - reference.openpacketcore.io
  resources:
  - sdkmanagednetworkfunctions/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - reference.openpacketcore.io
  resources:
  - sdkmanagednetworkfunctions/finalizers
  verbs:
  - update
