# Default values for sdk-reference-operator.
replicaCount: 1

image:
  repository: openpacketcore/sdk-reference-operator
  pullPolicy: IfNotPresent
  tag: ""

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

leaderElection:
  enabled: true

webhook:
  certMode: cert-manager
  caBundle: ""
  secretName: ""

metrics:
  enabled: true
  serviceMonitor:
    enabled: false

cliBridge:
  path: "/usr/local/bin/operator-lifecycle-cli"

workloadSynthesis:
  enabled: false

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
