[package]
name = "opc-proto-gre-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
opc-protocol = { path = "../../opc-protocol" }
opc-proto-gre = { path = ".." }
bytes = "1.8"

[workspace]

[[bin]]
name = "nwu"
path = "fuzz_targets/nwu.rs"
test = false
