apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sdk-reference-operator.fullname" . }}-manager-role
  labels:
    {{- include "sdk-reference-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - reference.openpacketcore.io
  resources:
  - sdkmanagednetworkfunctions
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - reference.openpacketcore.io
  resources:
  - sdkmanagednetworkfunctions/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - reference.openpacketcore.io
  resources:
  - sdkmanagednetworkfunctions/finalizers
  verbs:
  - update
{{- if .Values.workloadSynthesis.enabled }}
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sdk-reference-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "sdk-reference-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sdk-reference-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "sdk-reference-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.leaderElection.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sdk-reference-operator.fullname" . }}-leader-election-role
  labels:
    {{- include "sdk-reference-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sdk-reference-operator.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "sdk-reference-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sdk-reference-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "sdk-reference-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
