//! SDK-authored service proof for #770. Every model, registry, renderer,
//! applicator, diff, and validator below is generated by the test harness.

use std::sync::{Arc, Mutex};
use std::time::Duration;

use generated_test::{netconf_xml, netconf_xml_edit, schema_registry, types::*};
use opc_config_bus::{ConfigBus, MockManagedDatastore};
use opc_config_model::{AuthStrength, TransportType, TrustedPrincipal, WorkloadIdentity};
use opc_mgmt_audit::{AuditError, AuditEvent, AuditSink};
use opc_mgmt_authz::{AuthzError, ConfigWriteAuthorizer, PolicySource};
use opc_mgmt_limits::MgmtLimits;
use opc_mgmt_schema::{
    DefaultReport, NetconfXmlEditApplicator, NetconfXmlRenderer, SchemaRegistry,
};
use opc_nacm::{ModuleRegistry, NacmAction, NacmPolicy, NacmRule, PolicyVersion, YangPathPattern};
use opc_netconf_server::binding::{StartupDatastore, StartupDatastoreError};
use opc_netconf_server::{
    run_read_only_session_with_registry, NetconfConfigBinding, ReadOnlyNetconfServer,
    SessionConfig, SessionRegistry,
};
use opc_types::TenantId;
use tokio::io::{AsyncReadExt, AsyncWriteExt, DuplexStream};

const NS: &str = "urn:ietf:params:xml:ns:netconf:base:1.0";
const CANDIDATES: &str = "/ex:system/ex:access/ex:apn/ex:pgw-candidates";

#[derive(Clone)]
struct Policy(NacmPolicy);

impl PolicySource for Policy {
    fn active_policy(&self, _tenant: &str) -> Result<Arc<NacmPolicy>, AuthzError> {
        Ok(Arc::new(self.0.clone()))
    }
}

fn policy(deny_candidates: bool) -> Policy {
    let mut modules = ModuleRegistry::new();
    modules.register_module("example", "ex").unwrap();
    modules.register_module("wd-prefix-module", "wd").unwrap();
    modules.register_module("ietf-netconf", "nc").unwrap();
    let mut builder = NacmPolicy::builder(PolicyVersion::new(1));
    for action in [
        NacmAction::Create,
        NacmAction::Update,
        NacmAction::Replace,
        NacmAction::Delete,
    ] {
        if deny_candidates {
            builder = builder.add_rule(NacmRule::deny(
                action,
                YangPathPattern::parse(CANDIDATES, &modules).unwrap(),
            ));
        }
        for path in ["/ex:system", "/ex:system/**"] {
            builder = builder.add_rule(NacmRule::allow(
                action,
                YangPathPattern::parse(path, &modules).unwrap(),
            ));
        }
    }
    for path in ["/nc:edit-config", "/nc:commit", "/nc:close-session"] {
        builder = builder.add_rule(NacmRule::allow(
            NacmAction::Exec,
            YangPathPattern::parse(path, &modules).unwrap(),
        ));
    }
    Policy(builder.build())
}

#[derive(Clone, Default)]
struct Audit(Arc<Mutex<Vec<AuditEvent>>>);

impl AuditSink for Audit {
    fn record(&self, event: &AuditEvent) -> Result<(), AuditError> {
        self.0.lock().unwrap().push(event.clone());
        Ok(())
    }
}

struct Binding {
    bus: Arc<ConfigBus<System>>,
    edits_supported: bool,
    startup: Startup,
}

impl NetconfConfigBinding<System> for Binding {
    fn config_bus(&self) -> Arc<ConfigBus<System>> {
        Arc::clone(&self.bus)
    }
    fn schema_registry(&self) -> &'static dyn SchemaRegistry {
        schema_registry::registry()
    }
    fn writable_running_capability(&self) -> bool {
        true
    }
    fn candidate_datastore_capability(&self) -> bool {
        true
    }
    fn startup_datastore(&self) -> Option<&dyn StartupDatastore<System>> {
        Some(&self.startup)
    }
    fn generated_xml_renderer(&self) -> Option<&dyn NetconfXmlRenderer<System>> {
        Some(&netconf_xml::GeneratedNetconfXmlRenderer)
    }
    fn generated_xml_edit_applicator(&self) -> Option<&dyn NetconfXmlEditApplicator<System>> {
        self.edits_supported
            .then_some(&netconf_xml_edit::GeneratedNetconfXmlEditApplicator)
    }
}

#[derive(Clone)]
struct Startup(Arc<Mutex<Vec<System>>>);

impl StartupDatastore<System> for Startup {
    fn load_startup_config(&self) -> Result<Option<System>, StartupDatastoreError> {
        Ok(self.0.lock().unwrap().last().cloned())
    }

    fn store_startup_config(&self, config: &System) -> Result<(), StartupDatastoreError> {
        self.0.lock().unwrap().push(config.clone());
        Ok(())
    }
}

type Server = ReadOnlyNetconfServer<System, Binding, Policy, Audit>;

struct Fixture {
    server: Server,
    bus: Arc<ConfigBus<System>>,
    store: Arc<MockManagedDatastore<System>>,
    audit: Audit,
    startup: Startup,
}

impl Fixture {
    async fn new(running: System, deny_candidates: bool, edits_supported: bool) -> Self {
        let store = Arc::new(MockManagedDatastore::new());
        let startup = Startup(Arc::new(Mutex::new(vec![running.clone()])));
        let policy = policy(deny_candidates);
        let authorizer = Arc::new(
            ConfigWriteAuthorizer::new(schema_registry::registry(), policy.clone()).unwrap(),
        );
        let bus = Arc::new(
            ConfigBus::new(running, Arc::clone(&store), authorizer)
                .await
                .unwrap(),
        );
        let audit = Audit::default();
        let server = ReadOnlyNetconfServer::new(
            Binding {
                bus: Arc::clone(&bus),
                edits_supported,
                startup: startup.clone(),
            },
            policy,
            audit.clone(),
            TransportType::NetconfTls,
        )
        .unwrap();
        Self {
            server,
            bus,
            store,
            audit,
            startup,
        }
    }

    async fn rpc(&self, rpc: &str, limits: &MgmtLimits) -> String {
        self.rpc_sequence(&[rpc.to_string()], limits)
            .await
            .remove(0)
    }

    async fn rpc_sequence(&self, rpcs: &[String], limits: &MgmtLimits) -> Vec<String> {
        let sessions = SessionRegistry::new();
        let principal = TrustedPrincipal::new(
            WorkloadIdentity::User("fixture-operator".to_string()),
            TenantId::new("fixture").unwrap(),
        )
        .with_auth_strength(AuthStrength::MutualTls);
        let (mut client, mut stream) = tokio::io::duplex(65_536);
        let serving = run_read_only_session_with_registry(
            &self.server,
            &principal,
            &mut stream,
            SessionConfig {
                limits: limits.clone(),
                frame_timeout: Duration::from_secs(5),
            },
            1,
            &sessions,
        );
        let exchange = async {
            assert!(read_frame(&mut client).await.contains("<hello"));
            write_frame(&mut client, &format!(r#"<hello xmlns="{NS}"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability></capabilities></hello>"#)).await;
            let mut replies = Vec::new();
            for rpc in rpcs {
                write_frame(&mut client, rpc).await;
                replies.push(read_frame(&mut client).await);
            }
            write_frame(
                &mut client,
                &format!(r#"<rpc xmlns="{NS}" message-id="close"><close-session/></rpc>"#),
            )
            .await;
            assert!(read_frame(&mut client).await.contains("<ok/>"));
            replies
        };
        let (replies, result) = tokio::time::timeout(Duration::from_secs(5), async {
            tokio::join!(exchange, serving)
        })
        .await
        .unwrap();
        result.unwrap();
        replies
    }

    async fn rejected(&self, rpc: &str, tag: &str, limits: &MgmtLimits) {
        let before = self.bus.current_snapshot();
        let history_len = self.store.history().await.len();
        let startup_history = self.startup.0.lock().unwrap().clone();
        let reply = self.rpc(rpc, limits).await;
        assert!(
            reply.contains(&format!("<error-tag>{tag}</error-tag>")),
            "{reply}"
        );
        assert!(!reply.contains("<ok/>"));
        for value in ["fixture-apn", "fixture-private", "not-a-number", "65536"] {
            assert!(!reply.contains(value), "error replies must be value-free");
            assert!(
                !format!("{:?}", self.audit.0.lock().unwrap()).contains(value),
                "audit must be value-free"
            );
        }
        let after = self.bus.current_snapshot();
        assert_eq!(after.version, before.version);
        assert_eq!(after.tx_id, before.tx_id);
        assert!(
            Arc::ptr_eq(&after.config, &before.config),
            "rejection must not publish a snapshot"
        );
        assert_eq!(
            self.store.history().await.len(),
            history_len,
            "rejection must not persist a commit"
        );
        assert_eq!(
            *self.startup.0.lock().unwrap(),
            startup_history,
            "rejection must not write startup config"
        );
    }
}

async fn write_frame(stream: &mut DuplexStream, xml: &str) {
    stream.write_all(xml.as_bytes()).await.unwrap();
    stream.write_all(b"]]>]]>").await.unwrap();
}

async fn read_frame(stream: &mut DuplexStream) -> String {
    let mut bytes = Vec::new();
    loop {
        bytes.push(stream.read_u8().await.unwrap());
        assert!(bytes.len() <= 65_536);
        if bytes.ends_with(b"]]>]]>") {
            bytes.truncate(bytes.len() - 6);
            return String::from_utf8(bytes).unwrap();
        }
    }
}

fn complete_config() -> System {
    let mut config = System::default();
    config.hostname = LeafPresence::Explicit("fixture-system".to_string());
    for id in [7, 8, 9] {
        let mut gateway = Gateways::default();
        gateway.id = LeafPresence::Explicit(id);
        config.gateways.insert(id, gateway);
    }
    config.access = Some(Default::default());
    for (name, candidates) in [("fixture-apn-a", vec![7, 8]), ("fixture-apn-b", vec![8, 9])] {
        let mut apn = Apn::default();
        apn.name = LeafPresence::Explicit(name.to_string());
        apn.pgw_candidates = candidates;
        config
            .access
            .as_mut()
            .unwrap()
            .apn
            .insert(name.to_string(), apn);
    }
    config
}

fn edit(target: &str, body: &str, default: &str) -> String {
    format!(
        r#"<rpc xmlns="{NS}" xmlns:nc="{NS}" xmlns:ex="urn:example" message-id="770"><edit-config><target><{target}/></target><default-operation>{default}</default-operation><config>{body}</config></edit-config></rpc>"#
    )
}

fn nested(entries: &str) -> String {
    format!("<ex:system><ex:access><ex:apn><ex:name>fixture-apn-a</ex:name>{entries}</ex:apn></ex:access></ex:system>")
}

fn root_replacement(config: &System) -> String {
    // The shared generator fixture also has an intentionally unsupported
    // custom typedef for negative tests. It is empty in this complete config;
    // select every supported config descendant, including every nested list.
    let selection: Vec<_> = schema_registry::registry()
        .nodes()
        .iter()
        .filter(|node| node.config && node.path != "/ex:system/ex:custom-tags")
        .map(|node| node.path)
        .collect();
    let xml = netconf_xml::GeneratedNetconfXmlRenderer
        .render_running_config(config, &selection, DefaultReport::Explicit)
        .unwrap();
    let count: usize = config
        .access
        .as_ref()
        .unwrap()
        .apn
        .values()
        .map(|apn| apn.pgw_candidates.len())
        .sum();
    assert!(
        count >= 2,
        "the replacement fixture must exercise multiple leaf-list entries"
    );
    assert_eq!(
        xml.matches("<ex:pgw-candidates>").count(),
        count,
        "the full descendant selection must retain the real leaf-list fixture"
    );
    xml.replacen("<ex:system", "<ex:system nc:operation=\"replace\"", 1)
}

#[tokio::test]
async fn full_root_replace_commits_generated_nested_leaf_lists_from_no_config() {
    let fixture = Fixture::new(System::default(), false, true).await;
    assert!(fixture.store.history().await.is_empty());
    let expected = complete_config();
    let reply = fixture
        .rpc(
            &edit("running", &root_replacement(&expected), "merge"),
            &MgmtLimits::default(),
        )
        .await;
    assert!(reply.contains("<ok/>"), "{reply}");
    assert_eq!(fixture.bus.current_snapshot().config.as_ref(), &expected);
    let history = fixture.store.history().await;
    assert_eq!(history.len(), 1);
    assert_eq!(history[0].config, expected);
}

#[tokio::test]
async fn full_root_replace_removes_omitted_apns_and_rebuilds_the_collection() {
    let fixture = Fixture::new(complete_config(), false, true).await;
    let mut expected = complete_config();
    expected.hostname = LeafPresence::Absent;
    expected.gateways.remove(&7);
    let apns = &mut expected.access.as_mut().unwrap().apn;
    apns.remove("fixture-apn-b");
    apns.get_mut("fixture-apn-a").unwrap().pgw_candidates = vec![9, 8];
    let reply = fixture
        .rpc(
            &edit("running", &root_replacement(&expected), "merge"),
            &MgmtLimits::default(),
        )
        .await;
    assert!(reply.contains("<ok/>"), "{reply}");
    assert_eq!(fixture.bus.current_snapshot().config.as_ref(), &expected);
    assert_eq!(fixture.store.history().await[0].config, expected);
}

#[tokio::test]
async fn rejected_full_root_replacements_preserve_empty_and_populated_running() {
    let mut duplicate = complete_config();
    duplicate
        .access
        .as_mut()
        .unwrap()
        .apn
        .get_mut("fixture-apn-a")
        .unwrap()
        .pgw_candidates = vec![7, 7];
    let mut invalid = complete_config();
    invalid
        .access
        .as_mut()
        .unwrap()
        .apn
        .get_mut("fixture-apn-a")
        .unwrap()
        .pgw_candidates = vec![7, 10];
    for running in [System::default(), complete_config()] {
        let fixture = Fixture::new(running, false, true).await;
        for (config, tag) in [
            (&duplicate, "invalid-value"),
            (&invalid, "operation-failed"),
        ] {
            fixture
                .rejected(
                    &edit("running", &root_replacement(config), "merge"),
                    tag,
                    &MgmtLimits::default(),
                )
                .await;
        }
    }
}

#[tokio::test]
async fn rejected_candidate_edit_retains_the_previous_candidate_for_commit() {
    let fixture = Fixture::new(System::default(), false, true).await;
    let expected = complete_config();
    let invalid = nested(
        "<ex:pgw-candidates>7</ex:pgw-candidates><ex:pgw-candidates>007</ex:pgw-candidates>",
    );
    let replies = fixture
        .rpc_sequence(
            &[
                edit("candidate", &root_replacement(&expected), "merge"),
                edit("candidate", &invalid, "merge"),
                format!(r#"<rpc xmlns="{NS}" message-id="commit"><commit/></rpc>"#),
            ],
            &MgmtLimits::default(),
        )
        .await;
    assert!(replies[0].contains("<ok/>"), "{}", replies[0]);
    assert!(
        replies[1].contains("<error-tag>invalid-value</error-tag>"),
        "{}",
        replies[1]
    );
    assert!(replies[2].contains("<ok/>"), "{}", replies[2]);
    assert_eq!(fixture.bus.current_snapshot().config.as_ref(), &expected);
    let history = fixture.store.history().await;
    assert_eq!(
        history.len(),
        1,
        "candidate edits must not persist before commit"
    );
    assert_eq!(history[0].config, expected);
}

#[tokio::test]
async fn nested_leaf_list_entry_operations_preserve_unrelated_values() {
    let fixture = Fixture::new(complete_config(), false, true).await;
    for (entries, expected) in [
        ("<ex:pgw-candidates>7</ex:pgw-candidates><ex:pgw-candidates>9</ex:pgw-candidates>", vec![7, 8, 9]),
        ("<ex:pgw-candidates nc:operation=\"replace\">8</ex:pgw-candidates>", vec![7, 8, 9]),
        ("<ex:pgw-candidates nc:operation=\"delete\">7</ex:pgw-candidates><ex:pgw-candidates nc:operation=\"remove\">6</ex:pgw-candidates>", vec![8, 9]),
        ("<ex:pgw-candidates nc:operation=\"create\">7</ex:pgw-candidates>", vec![8, 9, 7]),
    ] {
        let reply = fixture.rpc(&edit("running", &nested(entries), "merge"), &MgmtLimits::default()).await;
        assert!(reply.contains("<ok/>"), "{reply}");
        let snapshot = fixture.bus.current_snapshot();
        let apns = &snapshot.config.access.as_ref().unwrap().apn;
        assert_eq!(apns["fixture-apn-a"].pgw_candidates, expected);
        assert_eq!(apns["fixture-apn-b"].pgw_candidates, vec![8, 9]);
    }
}

#[tokio::test]
async fn keyed_apn_replace_resets_only_that_leaf_list_collection() {
    let fixture = Fixture::new(complete_config(), false, true).await;
    let body =
        nested("<ex:pgw-candidates>9</ex:pgw-candidates><ex:pgw-candidates>7</ex:pgw-candidates>")
            .replace("<ex:apn>", "<ex:apn nc:operation=\"replace\">");
    let reply = fixture
        .rpc(&edit("running", &body, "merge"), &MgmtLimits::default())
        .await;
    assert!(reply.contains("<ok/>"), "{reply}");
    let snapshot = fixture.bus.current_snapshot();
    let apns = &snapshot.config.access.as_ref().unwrap().apn;
    assert_eq!(apns["fixture-apn-a"].pgw_candidates, vec![9, 7]);
    assert_eq!(apns["fixture-apn-b"].pgw_candidates, vec![8, 9]);
}

#[tokio::test]
async fn default_none_validates_values_without_mutating_the_leaf_list() {
    let fixture = Fixture::new(complete_config(), false, true).await;
    let before = fixture.bus.current_snapshot();
    let reply = fixture
        .rpc(
            &edit(
                "running",
                &nested("<ex:pgw-candidates>8</ex:pgw-candidates>"),
                "none",
            ),
            &MgmtLimits::default(),
        )
        .await;
    assert!(reply.contains("<ok/>"), "{reply}");
    assert_eq!(
        fixture.bus.current_snapshot().config.as_ref(),
        before.config.as_ref()
    );
    let body = nested("<ex:pgw-candidates>007</ex:pgw-candidates><ex:pgw-candidates nc:operation=\"merge\">7</ex:pgw-candidates>");
    fixture
        .rejected(
            &edit("running", &body, "none"),
            "invalid-value",
            &MgmtLimits::default(),
        )
        .await;
}

#[tokio::test]
async fn invalid_duplicate_and_conflicting_nested_values_never_commit() {
    let fixture = Fixture::new(complete_config(), false, true).await;
    for (entries, tag) in [
        ("<ex:pgw-candidates>not-a-number</ex:pgw-candidates>", "invalid-value"),
        ("<ex:pgw-candidates>65536</ex:pgw-candidates>", "invalid-value"),
        // Preserve the ConfigBus semantic-validation error classification.
        ("<ex:pgw-candidates>10</ex:pgw-candidates>", "operation-failed"),
        ("<ex:pgw-candidates>007</ex:pgw-candidates><ex:pgw-candidates>7</ex:pgw-candidates>", "invalid-value"),
        ("<ex:pgw-candidates nc:operation=\"delete\">7</ex:pgw-candidates><ex:pgw-candidates nc:operation=\"merge\">007</ex:pgw-candidates>", "invalid-value"),
        ("<ex:pgw-candidates><ex:name>fixture-private</ex:name></ex:pgw-candidates>", "invalid-value"),
    ] {
        // A valid earlier mutation must not escape an eventual rejection.
        let body = nested(entries).replacen("<ex:system>", "<ex:system><ex:hostname>fixture-private</ex:hostname>", 1);
        fixture.rejected(&edit("running", &body, "merge"), tag, &MgmtLimits::default()).await;
    }
}

#[tokio::test]
async fn repeated_parents_cannot_bypass_leaf_list_conflict_detection() {
    let fixture = Fixture::new(complete_config(), false, true).await;
    for body in [
        "<ex:system><ex:access><ex:apn><ex:name>fixture-apn-a</ex:name><ex:pgw-candidates nc:operation=\"delete\">7</ex:pgw-candidates></ex:apn><ex:apn><ex:name>fixture-apn-a</ex:name><ex:pgw-candidates>007</ex:pgw-candidates></ex:apn></ex:access></ex:system>",
        "<ex:system><ex:access><ex:apn><ex:name>fixture-apn-a</ex:name><ex:pgw-candidates nc:operation=\"delete\">7</ex:pgw-candidates></ex:apn></ex:access><ex:access><ex:apn><ex:name>fixture-apn-a</ex:name><ex:pgw-candidates>7</ex:pgw-candidates></ex:apn></ex:access></ex:system>",
        "<ex:system nc:operation=\"replace\"><ex:gateways><ex:id>007</ex:id></ex:gateways><ex:gateways><ex:id>7</ex:id></ex:gateways></ex:system>",
    ] {
        fixture.rejected(&edit("running", body, "merge"), "invalid-value", &MgmtLimits::default()).await;
    }
}

#[tokio::test]
async fn leaf_list_existence_errors_keep_netconf_error_distinctions() {
    let fixture = Fixture::new(complete_config(), false, true).await;
    for target in ["running", "candidate", "startup"] {
        for (operation, value, tag) in [
            ("create", "7", "data-exists"),
            ("delete", "9", "data-missing"),
        ] {
            let entries = format!(
                "<ex:pgw-candidates nc:operation=\"{operation}\">{value}</ex:pgw-candidates>"
            );
            fixture
                .rejected(
                    &edit(target, &nested(&entries), "merge"),
                    tag,
                    &MgmtLimits::default(),
                )
                .await;
        }
    }
}

#[tokio::test]
async fn unauthorized_unsupported_and_over_limit_edits_never_commit() {
    let denied = Fixture::new(System::default(), true, true).await;
    denied
        .rejected(
            &edit("running", &root_replacement(&complete_config()), "merge"),
            "access-denied",
            &MgmtLimits::default(),
        )
        .await;
    let unsupported = Fixture::new(complete_config(), false, false).await;
    unsupported
        .rejected(
            &edit(
                "running",
                &nested("<ex:pgw-candidates>9</ex:pgw-candidates>"),
                "merge",
            ),
            "operation-not-supported",
            &MgmtLimits::default(),
        )
        .await;
    let fixture = Fixture::new(complete_config(), false, true).await;
    fixture
        .rejected(
            &edit(
                "running",
                "<ex:system><ex:custom-tags>fixture-private</ex:custom-tags></ex:system>",
                "merge",
            ),
            "invalid-value",
            &MgmtLimits::default(),
        )
        .await;
    let mut limits = MgmtLimits::default();
    limits.max_paths_per_request = 5;
    fixture.rejected(&edit("running", &nested("<ex:pgw-candidates>7</ex:pgw-candidates><ex:pgw-candidates>8</ex:pgw-candidates>"), "merge"), "too-big", &limits).await;
    limits = MgmtLimits::default();
    limits.max_value_bytes = 64;
    let oversized = format!("<ex:pgw-candidates>{}</ex:pgw-candidates>", "7".repeat(65));
    fixture
        .rejected(
            &edit("running", &nested(&oversized), "merge"),
            "too-big",
            &limits,
        )
        .await;
}
